/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.util.Date;


/**
 * @project sqltoy-showcase
 * @version 1.0.0
 * Table: sys_cardapp_info   
 */
@Entity(tableName="sys_cardapp_info",pk_constraint="PRIMARY")
public abstract class AbstractCardappInfoVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //cardappId,terminalId,cardAppType,merchantCode,termNo,mccCode,mccType,signOrg,status,createTm,createUser,lastModifyTm,cardappCloseDate
	 
	 //not null properties
	 //cardappId

	/**
	 * 
	 */
	private static final long serialVersionUID = 8524096800717825263L;
	
	@Id(strategy="assign")
	@Column(name="CARDAPP_ID",length=10L,type=java.sql.Types.INTEGER,nullable=false)
	protected Integer cardappId;
	
	@Column(name="TERMINAL_ID",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer terminalId;
	
	/**
	 * 卡应用类型，对应数据字典类型CARD_APP_NAMES,对照DICT_KEY字段取COMMENTS的值
	 */
	@Column(name="CARD_APP_TYPE",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer cardAppType;
	
	@Column(name="MERCHANT_CODE",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String merchantCode;
	
	@Column(name="TERM_NO",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String termNo;
	
	/**
	 * 商户类别(行业类别),从SYS_MCC_INFO表翻译
	 */
	@Column(name="MCC_CODE",length=5L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String mccCode;
	
	/**
	 * DD统计大类 报表统计需要的自定义维度。对应数据字典表类型MER_TYPE
	 */
	@Column(name="MCC_TYPE",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String mccType;
	
	/**
	 * 签约机构 对应机构表SYS_ORGAN_INFO
	 */
	@Column(name="SIGN_ORG",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer signOrg;
	
	@Column(name="STATUS",length=50L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String status;
	
	@Column(name="CREATE_TM",length=10L,type=java.sql.Types.DATE,nullable=true)
	protected Date createTm;
	
	@Column(name="CREATE_USER",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer createUser;
	
	@Column(name="LAST_MODIFY_TM",length=10L,type=java.sql.Types.DATE,nullable=true)
	protected Date lastModifyTm;
	
	@Column(name="CARDAPP_CLOSE_DATE",length=10L,type=java.sql.Types.DATE,nullable=true)
	protected Date cardappCloseDate;
	


	/** default constructor */
	public AbstractCardappInfoVO() {
	}
	
	/** pk constructor */
	public AbstractCardappInfoVO(Integer cardappId)
	{
		this.cardappId=cardappId;
	}


	/** full constructor */
	public AbstractCardappInfoVO(Integer cardappId,Integer terminalId,Integer cardAppType,String merchantCode,String termNo,String mccCode,String mccType,Integer signOrg,String status,Date createTm,Integer createUser,Date lastModifyTm,Date cardappCloseDate)
	{
		this.cardappId=cardappId;
		this.terminalId=terminalId;
		this.cardAppType=cardAppType;
		this.merchantCode=merchantCode;
		this.termNo=termNo;
		this.mccCode=mccCode;
		this.mccType=mccType;
		this.signOrg=signOrg;
		this.status=status;
		this.createTm=createTm;
		this.createUser=createUser;
		this.lastModifyTm=lastModifyTm;
		this.cardappCloseDate=cardappCloseDate;
	}
	
	/**
	 *@param cardappId the cardappId to set
	 */
	public void setCardappId(Integer cardappId) {
		this.cardappId=cardappId;
	}
		
	/**
	 *@return the CardappId
	 */
	public Integer getCardappId() {
	    return this.cardappId;
	}
	
	/**
	 *@param terminalId the terminalId to set
	 */
	public void setTerminalId(Integer terminalId) {
		this.terminalId=terminalId;
	}
		
	/**
	 *@return the TerminalId
	 */
	public Integer getTerminalId() {
	    return this.terminalId;
	}
	
	/**
	 *@param cardAppType the cardAppType to set
	 */
	public void setCardAppType(Integer cardAppType) {
		this.cardAppType=cardAppType;
	}
		
	/**
	 *@return the CardAppType
	 */
	public Integer getCardAppType() {
	    return this.cardAppType;
	}
	
	/**
	 *@param merchantCode the merchantCode to set
	 */
	public void setMerchantCode(String merchantCode) {
		this.merchantCode=merchantCode;
	}
		
	/**
	 *@return the MerchantCode
	 */
	public String getMerchantCode() {
	    return this.merchantCode;
	}
	
	/**
	 *@param termNo the termNo to set
	 */
	public void setTermNo(String termNo) {
		this.termNo=termNo;
	}
		
	/**
	 *@return the TermNo
	 */
	public String getTermNo() {
	    return this.termNo;
	}
	
	/**
	 *@param mccCode the mccCode to set
	 */
	public void setMccCode(String mccCode) {
		this.mccCode=mccCode;
	}
		
	/**
	 *@return the MccCode
	 */
	public String getMccCode() {
	    return this.mccCode;
	}
	
	/**
	 *@param mccType the mccType to set
	 */
	public void setMccType(String mccType) {
		this.mccType=mccType;
	}
		
	/**
	 *@return the MccType
	 */
	public String getMccType() {
	    return this.mccType;
	}
	
	/**
	 *@param signOrg the signOrg to set
	 */
	public void setSignOrg(Integer signOrg) {
		this.signOrg=signOrg;
	}
		
	/**
	 *@return the SignOrg
	 */
	public Integer getSignOrg() {
	    return this.signOrg;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(String status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public String getStatus() {
	    return this.status;
	}
	
	/**
	 *@param createTm the createTm to set
	 */
	public void setCreateTm(Date createTm) {
		this.createTm=createTm;
	}
		
	/**
	 *@return the CreateTm
	 */
	public Date getCreateTm() {
	    return this.createTm;
	}
	
	/**
	 *@param createUser the createUser to set
	 */
	public void setCreateUser(Integer createUser) {
		this.createUser=createUser;
	}
		
	/**
	 *@return the CreateUser
	 */
	public Integer getCreateUser() {
	    return this.createUser;
	}
	
	/**
	 *@param lastModifyTm the lastModifyTm to set
	 */
	public void setLastModifyTm(Date lastModifyTm) {
		this.lastModifyTm=lastModifyTm;
	}
		
	/**
	 *@return the LastModifyTm
	 */
	public Date getLastModifyTm() {
	    return this.lastModifyTm;
	}
	
	/**
	 *@param cardappCloseDate the cardappCloseDate to set
	 */
	public void setCardappCloseDate(Date cardappCloseDate) {
		this.cardappCloseDate=cardappCloseDate;
	}
		
	/**
	 *@return the CardappCloseDate
	 */
	public Date getCardappCloseDate() {
	    return this.cardappCloseDate;
	}



	/**
     * @todo vo columns to String
     */
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("cardappId=").append(getCardappId()).append("\n");
		columnsBuffer.append("terminalId=").append(getTerminalId()).append("\n");
		columnsBuffer.append("cardAppType=").append(getCardAppType()).append("\n");
		columnsBuffer.append("merchantCode=").append(getMerchantCode()).append("\n");
		columnsBuffer.append("termNo=").append(getTermNo()).append("\n");
		columnsBuffer.append("mccCode=").append(getMccCode()).append("\n");
		columnsBuffer.append("mccType=").append(getMccType()).append("\n");
		columnsBuffer.append("signOrg=").append(getSignOrg()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		columnsBuffer.append("createTm=").append(getCreateTm()).append("\n");
		columnsBuffer.append("createUser=").append(getCreateUser()).append("\n");
		columnsBuffer.append("lastModifyTm=").append(getLastModifyTm()).append("\n");
		columnsBuffer.append("cardappCloseDate=").append(getCardappCloseDate()).append("\n");
		return columnsBuffer.toString();
	}
}
