/**
 *@Generated by sagacity-quickvo 4.0
 */
package sqltoy.showcase.system.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.util.Date;


/**
 * @project sqltoy-showcase
 * @version 1.0.0
 * Table: sys_unpivot_data,Remark:行转列测试   
 */
@Entity(tableName="sys_unpivot_data",pk_constraint="PRIMARY")
public abstract class AbstractUnpivotDataVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //transDate,totalAmount,personAmount,companyAmount
	 
	 //not null properties
	 //transDate,totalAmount,personAmount,companyAmount

	/**
	 * 
	 */
	private static final long serialVersionUID = 1995265734237380277L;
	
	/**
	 * 交易日期
	 */
	@Id(strategy="assign")
	@Column(name="TRANS_DATE",length=10L,type=java.sql.Types.DATE,nullable=false)
	protected Date transDate;
	
	/**
	 * 交易总金额
	 */
	@Column(name="TOTAL_AMOUNT",length=10L,type=java.sql.Types.DOUBLE,nullable=false)
	protected Double totalAmount;
	
	/**
	 * 个人交易金额
	 */
	@Column(name="PERSON_AMOUNT",length=10L,type=java.sql.Types.DOUBLE,nullable=false)
	protected Double personAmount;
	
	/**
	 * 企业交易金额
	 */
	@Column(name="COMPANY_AMOUNT",length=10L,type=java.sql.Types.DOUBLE,nullable=false)
	protected Double companyAmount;
	


	/** default constructor */
	public AbstractUnpivotDataVO() {
	}
	
	/** pk constructor */
	public AbstractUnpivotDataVO(Date transDate)
	{
		this.transDate=transDate;
	}


	/** full constructor */
	public AbstractUnpivotDataVO(Date transDate,Double totalAmount,Double personAmount,Double companyAmount)
	{
		this.transDate=transDate;
		this.totalAmount=totalAmount;
		this.personAmount=personAmount;
		this.companyAmount=companyAmount;
	}
	
	/**
	 *@param transDate the transDate to set
	 */
	public void setTransDate(Date transDate) {
		this.transDate=transDate;
	}
		
	/**
	 *@return the TransDate
	 */
	public Date getTransDate() {
	    return this.transDate;
	}
	
	/**
	 *@param totalAmount the totalAmount to set
	 */
	public void setTotalAmount(Double totalAmount) {
		this.totalAmount=totalAmount;
	}
		
	/**
	 *@return the TotalAmount
	 */
	public Double getTotalAmount() {
	    return this.totalAmount;
	}
	
	/**
	 *@param personAmount the personAmount to set
	 */
	public void setPersonAmount(Double personAmount) {
		this.personAmount=personAmount;
	}
		
	/**
	 *@return the PersonAmount
	 */
	public Double getPersonAmount() {
	    return this.personAmount;
	}
	
	/**
	 *@param companyAmount the companyAmount to set
	 */
	public void setCompanyAmount(Double companyAmount) {
		this.companyAmount=companyAmount;
	}
		
	/**
	 *@return the CompanyAmount
	 */
	public Double getCompanyAmount() {
	    return this.companyAmount;
	}



	/**
     * @todo vo columns to String
     */
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("transDate=").append(getTransDate()).append("\n");
		columnsBuffer.append("totalAmount=").append(getTotalAmount()).append("\n");
		columnsBuffer.append("personAmount=").append(getPersonAmount()).append("\n");
		columnsBuffer.append("companyAmount=").append(getCompanyAmount()).append("\n");
		return columnsBuffer.toString();
	}
}
