/**
 *@Generated by QuickVO Tools 1.5 
 */
package org.sagacity.sqltoy.demo.vo.base;

import java.io.Serializable;

import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;


/**
 * @project sqltoy-orm
 * @version 1.0.0
 * 员工技能组    			
 * StaffGroupVO generated by SYS_STAFF_GROUP
 */
@Entity(tableName="SYS_STAFF_GROUP")
public abstract class AbstractStaffGroupVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //staffId,groupId,techLevel,isMajor
	 
	 //not null properties
	 //staffId,groupId,isMajor

	/**
	 * 员工ID
	 */
	@Id
	@Column(name="STAFF_ID",type=java.sql.Types.VARCHAR,nullable=false)
	protected String staffId;
	
	/**
	 * 技能组编号
	 */
	@Id
	@Column(name="GROUP_ID",type=java.sql.Types.VARCHAR,nullable=false)
	protected String groupId;
	
	/**
	 * DD技能等级
	 */
	@Column(name="TECH_LEVEL",type=java.sql.Types.INTEGER,nullable=true)
	protected Integer techLevel;
	
	/**
	 * 是否主要技能组
	 */
	@Column(name="IS_MAJOR",defaultValue="0",type=java.sql.Types.INTEGER,nullable=false)
	protected Integer isMajor;
	


	/** default constructor */
	public AbstractStaffGroupVO() {
	}
	
	/** pk constructor */
	public AbstractStaffGroupVO(String staffId,String groupId)
	{
		this.staffId=staffId;
		this.groupId=groupId;
	}

	/** minimal constructor */
	public AbstractStaffGroupVO(String staffId,String groupId,Integer isMajor)
	{
		this.staffId=staffId;
		this.groupId=groupId;
		this.isMajor=isMajor;
	}

	/** full constructor */
	public AbstractStaffGroupVO(String staffId,String groupId,Integer techLevel,Integer isMajor)
	{
		this.staffId=staffId;
		this.groupId=groupId;
		this.techLevel=techLevel;
		this.isMajor=isMajor;
	}
	
	/**
	 *@param staffId the staffId to set
	 */
	public void setStaffId(String staffId) {
		this.staffId=staffId;
	}
		
	/**
	 *@return the StaffId
	 */
	public String getStaffId() {
	    return this.staffId;
	}
	
	/**
	 *@param groupId the groupId to set
	 */
	public void setGroupId(String groupId) {
		this.groupId=groupId;
	}
		
	/**
	 *@return the GroupId
	 */
	public String getGroupId() {
	    return this.groupId;
	}
	
	/**
	 *@param techLevel the techLevel to set
	 */
	public void setTechLevel(Integer techLevel) {
		this.techLevel=techLevel;
	}
		
	/**
	 *@return the TechLevel
	 */
	public Integer getTechLevel() {
	    return this.techLevel;
	}
	
	/**
	 *@param isMajor the isMajor to set
	 */
	public void setIsMajor(Integer isMajor) {
		this.isMajor=isMajor;
	}
		
	/**
	 *@return the IsMajor
	 */
	public Integer getIsMajor() {
	    return this.isMajor;
	}




	/**
     * @todo vo columns to String
     */
	public String toString() {
		StringBuffer columnsBuffer=new StringBuffer();
		columnsBuffer.append("staffId=").append(getStaffId()).append("\n");
		columnsBuffer.append("groupId=").append(getGroupId()).append("\n");
		columnsBuffer.append("techLevel=").append(getTechLevel()).append("\n");
		columnsBuffer.append("isMajor=").append(getIsMajor()).append("\n");
		return columnsBuffer.toString();
	}
}
