package org.sagacity.sqltoy.plugins.ddl.impl;

import java.util.Locale;

import org.sagacity.sqltoy.model.ColumnMeta;
import org.sagacity.sqltoy.model.TableMeta;
import org.sagacity.sqltoy.plugins.ddl.DDLUtils;
import org.sagacity.sqltoy.plugins.ddl.DialectDDLGenerator;
import org.sagacity.sqltoy.utils.StringUtil;

/**
 * @project sagacity-sqltoy
 * @description SAP HANA数据库建表DDL: identity用GENERATED BY DEFAULT AS IDENTITY,
 *              注释走独立COMMENT ON语句,时间默认值CURRENT_TIMESTAMP,
 *              计算列用GENERATED ALWAYS AS(HANA为存储型)
 * @author zhongxuchen
 * @version v1.0,Date:2026-09-19
 */
public class HanaDDLGenerator implements DialectDDLGenerator {
	private String NEWLINE = "\r\n";
	private String TAB = "   ";

	@Override
	public String createTableSql(TableMeta tableMeta, String schema, String upperOrLower, int dbType) {
		if (tableMeta == null) {
			return null;
		}
		StringBuilder tableSql = new StringBuilder();
		String tableName = StringUtil.toLowerOrUpper(tableMeta.getTableName(), upperOrLower);
		if (StringUtil.isNotBlank(schema)) {
			tableName = schema + "." + tableName;
		}
		tableSql.append("CREATE TABLE ").append(tableName).append(NEWLINE);
		tableSql.append("(").append(NEWLINE);
		int index = 0;
		for (ColumnMeta colMeta : tableMeta.getColumns()) {
			if (index > 0) {
				tableSql.append(",").append(NEWLINE);
			}
			tableSql.append(TAB).append(StringUtil.toLowerOrUpper(colMeta.getColName(), upperOrLower));
			tableSql.append(" ").append(DDLUtils.convertType(colMeta, dbType));
			// 计算列:HANA SQL表层的GENERATED ALWAYS AS为存储型
			if (colMeta.getGeneratedType() > 0 && StringUtil.isNotBlank(colMeta.getDefaultValue())) {
				tableSql.append(" GENERATED ALWAYS AS (").append(colMeta.getDefaultValue()).append(")");
			}
			// 自增:HANA identity语法
			else if (colMeta.isAutoIncrement()) {
				tableSql.append(" GENERATED BY DEFAULT AS IDENTITY");
			} else if (colMeta.getGeneratedType() == 0 && StringUtil.isNotBlank(colMeta.getDefaultValue())) {
				tableSql.append(" DEFAULT ");
				if (DDLUtils.isNotChar(colMeta.getDataType())) {
					tableSql.append(colMeta.getDefaultValue());
				} else if (DDLUtils.isDate(colMeta.getDataType())
						&& DDLUtils.isDateFunction(colMeta.getDefaultValue().toUpperCase(Locale.ROOT))) {
					tableSql.append(colMeta.getDefaultValue());
				} else {
					tableSql.append("'").append(colMeta.getDefaultValue()).append("'");
				}
			}
			if (!colMeta.isNullable()) {
				tableSql.append(" NOT NULL");
			}
			index++;
		}
		// 主键
		DDLUtils.wrapTablePrimaryKeys(tableMeta, upperOrLower, dbType, tableSql);
		tableSql.append(NEWLINE).append(")");
		// 分区(HANA分区元数据不暴露于系统视图,分区明细以注释形式)
		DDLUtils.wrapTablePartition(tableMeta, upperOrLower, dbType, tableSql);
		// 表和字段注释:HANA走独立COMMENT ON语句
		DDLUtils.wrapTableAndColumnsComment(tableMeta, upperOrLower, dbType, tableSql);
		// 索引
		DDLUtils.wrapTableIndexes(tableMeta, upperOrLower, dbType, tableSql, true);
		// 外键
		DDLUtils.wrapForeignKeys(tableMeta, upperOrLower, dbType, tableSql, true);
		return tableSql.toString();
	}
}
