package org.sagacity.sqltoy.plugins.ddl.impl;

import java.util.Locale;

import org.sagacity.sqltoy.model.ColumnMeta;
import org.sagacity.sqltoy.model.TableMeta;
import org.sagacity.sqltoy.plugins.ddl.DDLUtils;
import org.sagacity.sqltoy.plugins.ddl.DialectDDLGenerator;
import org.sagacity.sqltoy.utils.DataSourceUtils.DBType;
import org.sagacity.sqltoy.utils.StringUtil;

/**
 * @project sagacity-sqltoy
 * @description oracle数据库
 * @author zhongxuchen
 * @version v1.0,Date:2023-12-27
 * @modify Date:2023-12-27,修改说明
 */
public class OracleDDLGenerator implements DialectDDLGenerator {
	private String NEWLINE = "\r\n";
	private String TAB = "   ";

	/**
	 * 生成创建表sql
	 */
	public String createTableSql(TableMeta tableMeta, String schema, String upperOrLower, int dbType) {
		if (tableMeta == null) {
			return null;
		}
		StringBuilder tableSql = new StringBuilder();
		String tableName = StringUtil.toLowerOrUpper(tableMeta.getTableName(), upperOrLower);
		tableSql.append("CREATE TABLE ").append(tableName).append(NEWLINE);
		tableSql.append("(").append(NEWLINE);
		int index = 0;
		for (ColumnMeta colMeta : tableMeta.getColumns()) {
			if (index > 0) {
				tableSql.append(",").append(NEWLINE);
			}
			// 字段名
			tableSql.append(TAB).append(StringUtil.toLowerOrUpper(colMeta.getColName(), upperOrLower));
			// 类型:Oracle/DM的VARCHAR上限32767,超长降级CLOB;DM不支持TEXT/DOUBLE PRECISION
			String colType = DDLUtils.convertType(colMeta, dbType);
			if (colType.startsWith("VARCHAR")) {
				int open = colType.indexOf('(');
				int close = colType.indexOf(')', open);
				if (open > 0 && close > open) {
					try {
						if (Integer.parseInt(colType.substring(open + 1, close).trim()) > 32767) {
							colType = "CLOB";
						}
					} catch (NumberFormatException ignore) {
					}
				}
			}
			// DM不支持TEXT(用CLOB)和DOUBLE PRECISION(用DOUBLE)
			if (dbType == DBType.DM) {
				if (colType.equals("TEXT")) {
					colType = "CLOB";
				} else if (colType.equals("DOUBLE PRECISION")) {
					colType = "DOUBLE";
				}
			}
			tableSql.append(" ").append(colType);
			// 计算列
			if (colMeta.getGeneratedType() > 0 && StringUtil.isNotBlank(colMeta.getDefaultValue())) {
				tableSql.append(" GENERATED ALWAYS AS (").append(colMeta.getDefaultValue()).append(") ");
			}
			// 自增:DM用IDENTITY(1,1);oracle 12c+用GENERATED BY DEFAULT AS IDENTITY;
			// oracle 11g无内联自增语法(需trigger+sequence),跳过内联子句避免ORA-02000(列退化为普通NUMBER)
			if (colMeta.isAutoIncrement()) {
				if (dbType == DBType.DM) {
					tableSql.append(" IDENTITY(1,1)");
				} else if (dbType != DBType.ORACLE11) {
					tableSql.append(" GENERATED BY DEFAULT AS IDENTITY ");
				}
			} else if (colMeta.getGeneratedType() == 0 && StringUtil.isNotBlank(colMeta.getDefaultValue())) {
				tableSql.append(" DEFAULT ");
				if (DDLUtils.isNotChar(colMeta.getDataType())) {
					tableSql.append(colMeta.getDefaultValue());
				} else if (DDLUtils.isDate(colMeta.getDataType())
						&& DDLUtils.isDateFunction(colMeta.getDefaultValue().toUpperCase(Locale.ROOT))) {
					tableSql.append(colMeta.getDefaultValue());
				} else {
					tableSql.append("'").append(colMeta.getDefaultValue()).append("'");
				}
			}
			// 是否为null(oracle语法要求default在not null之前)
			if (!colMeta.isNullable()) {
				tableSql.append(" NOT NULL");
			}
			index++;
		}
		// 主键
		DDLUtils.wrapTablePrimaryKeys(tableMeta, upperOrLower, dbType, tableSql);
		tableSql.append(NEWLINE);
		tableSql.append(")");
		// 分区子句
		DDLUtils.wrapTablePartition(tableMeta, upperOrLower, dbType, tableSql);
		// 表和字段的备注
		DDLUtils.wrapTableAndColumnsComment(tableMeta, upperOrLower, dbType, tableSql);
		// 索引
		DDLUtils.wrapTableIndexes(tableMeta, upperOrLower, dbType, tableSql, true);
		// 外键
		DDLUtils.wrapForeignKeys(tableMeta, upperOrLower, dbType, tableSql, true);
		return tableSql.toString();
	}
}
