/**
 *@Generated by sagacity-quickvo 4.0
 */
package sqltoy.showcase.system.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.util.Date;


/**
 * @project sqltoy-showcase
 * @version 1.0.0
 * Table: sys_summary_case,Remark:汇总计算演示表   
 */
@Entity(tableName="sys_summary_case",pk_constraint="PRIMARY")
public abstract class AbstractSummaryCaseVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //transId,transDate,transChannel,transCode,transAmt
	 
	 //not null properties
	 //transId,transDate,transChannel,transAmt

	/**
	 * 
	 */
	private static final long serialVersionUID = 7769667587707470399L;
	
	/**
	 * 交易流水号
	 */
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugin.id.DefaultIdGenerator")
	@Column(name="TRANS_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String transId;
	
	/**
	 * 交易日期
	 */
	@Column(name="TRANS_DATE",length=10L,type=java.sql.Types.DATE,nullable=false)
	protected Date transDate;
	
	/**
	 * 交易渠道
	 */
	@Column(name="TRANS_CHANNEL",length=20L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String transChannel;
	
	/**
	 * 交易代码
	 */
	@Column(name="TRANS_CODE",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String transCode;
	
	/**
	 * 交易金额
	 */
	@Column(name="TRANS_AMT",length=12L,type=java.sql.Types.DOUBLE,nullable=false)
	protected Double transAmt;
	


	/** default constructor */
	public AbstractSummaryCaseVO() {
	}
	
	/** pk constructor */
	public AbstractSummaryCaseVO(String transId)
	{
		this.transId=transId;
	}

	/** minimal constructor */
	public AbstractSummaryCaseVO(String transId,Date transDate,String transChannel,Double transAmt)
	{
		this.transId=transId;
		this.transDate=transDate;
		this.transChannel=transChannel;
		this.transAmt=transAmt;
	}

	/** full constructor */
	public AbstractSummaryCaseVO(String transId,Date transDate,String transChannel,String transCode,Double transAmt)
	{
		this.transId=transId;
		this.transDate=transDate;
		this.transChannel=transChannel;
		this.transCode=transCode;
		this.transAmt=transAmt;
	}
	
	/**
	 *@param transId the transId to set
	 */
	public void setTransId(String transId) {
		this.transId=transId;
	}
		
	/**
	 *@return the TransId
	 */
	public String getTransId() {
	    return this.transId;
	}
	
	/**
	 *@param transDate the transDate to set
	 */
	public void setTransDate(Date transDate) {
		this.transDate=transDate;
	}
		
	/**
	 *@return the TransDate
	 */
	public Date getTransDate() {
	    return this.transDate;
	}
	
	/**
	 *@param transChannel the transChannel to set
	 */
	public void setTransChannel(String transChannel) {
		this.transChannel=transChannel;
	}
		
	/**
	 *@return the TransChannel
	 */
	public String getTransChannel() {
	    return this.transChannel;
	}
	
	/**
	 *@param transCode the transCode to set
	 */
	public void setTransCode(String transCode) {
		this.transCode=transCode;
	}
		
	/**
	 *@return the TransCode
	 */
	public String getTransCode() {
	    return this.transCode;
	}
	
	/**
	 *@param transAmt the transAmt to set
	 */
	public void setTransAmt(Double transAmt) {
		this.transAmt=transAmt;
	}
		
	/**
	 *@return the TransAmt
	 */
	public Double getTransAmt() {
	    return this.transAmt;
	}



	/**
     * @todo vo columns to String
     */
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("transId=").append(getTransId()).append("\n");
		columnsBuffer.append("transDate=").append(getTransDate()).append("\n");
		columnsBuffer.append("transChannel=").append(getTransChannel()).append("\n");
		columnsBuffer.append("transCode=").append(getTransCode()).append("\n");
		columnsBuffer.append("transAmt=").append(getTransAmt()).append("\n");
		return columnsBuffer.toString();
	}
}
