/**
 *@Generated by sagacity-quickvo 4.0
 */
package sqltoy.showcase.system.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.util.Date;

import org.sagacity.sqltoy.config.annotation.OneToMany;
import java.util.List;
import java.util.ArrayList;
import sqltoy.showcase.system.vo.MultpkItemVO;

/**
 * @project sqltoy-showcase
 * @version 1.0.0
 * Table: sys_multpk_main,Remark:复合主键关联主表   
 */
@Entity(tableName="sys_multpk_main",pk_constraint="PRIMARY")
public abstract class AbstractMultpkMainVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //bizType,batchNo,amount,createTime
	 
	 //not null properties
	 //bizType,batchNo,amount,createTime

	/**
	 * 
	 */
	private static final long serialVersionUID = 9023483812325093671L;
	
	/**
	 * 业务分类编号
	 */
	@Id
	@Column(name="BIZ_TYPE",length=20L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String bizType;
	
	/**
	 * 批次号
	 */
	@Id
	@Column(name="BATCH_NO",length=10L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String batchNo;
	
	/**
	 * 交易金额
	 */
	@Column(name="AMOUNT",length=12L,type=java.sql.Types.DOUBLE,nullable=false)
	protected Double amount;
	
	/**
	 * 创建日期
	 */
	@Column(name="CREATE_TIME",length=10L,type=java.sql.Types.DATE,nullable=false)
	protected Date createTime;
	

	/**
	 * 主键关联子表信息
	 */
	@OneToMany(fields={"bizType","batchNo"},mappedTable="sys_multpk_item",mappedColumns={"BIZ_TYPE","BATCH_NO"},mappedFields={"bizType","batchNo"},delete=false)
	protected List<MultpkItemVO> multpkItemVOs=new ArrayList<MultpkItemVO>();


	/** default constructor */
	public AbstractMultpkMainVO() {
	}
	
	/** pk constructor */
	public AbstractMultpkMainVO(String bizType,String batchNo)
	{
		this.bizType=bizType;
		this.batchNo=batchNo;
	}


	/** full constructor */
	public AbstractMultpkMainVO(String bizType,String batchNo,Double amount,Date createTime)
	{
		this.bizType=bizType;
		this.batchNo=batchNo;
		this.amount=amount;
		this.createTime=createTime;
	}
	
	/**
	 *@param bizType the bizType to set
	 */
	public void setBizType(String bizType) {
		this.bizType=bizType;
	}
		
	/**
	 *@return the BizType
	 */
	public String getBizType() {
	    return this.bizType;
	}
	
	/**
	 *@param batchNo the batchNo to set
	 */
	public void setBatchNo(String batchNo) {
		this.batchNo=batchNo;
	}
		
	/**
	 *@return the BatchNo
	 */
	public String getBatchNo() {
	    return this.batchNo;
	}
	
	/**
	 *@param amount the amount to set
	 */
	public void setAmount(Double amount) {
		this.amount=amount;
	}
		
	/**
	 *@return the Amount
	 */
	public Double getAmount() {
	    return this.amount;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public Date getCreateTime() {
	    return this.createTime;
	}


	/**
	 * @return the multpkItemVOs
	 */
	public List<MultpkItemVO> getMultpkItemVOs() {
		return this.multpkItemVOs;
	}
	
	public void setMultpkItemVOs(List<MultpkItemVO> multpkItemVOs)	{
		this.multpkItemVOs=multpkItemVOs;
	}

	/**
     * @todo vo columns to String
     */
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("bizType=").append(getBizType()).append("\n");
		columnsBuffer.append("batchNo=").append(getBatchNo()).append("\n");
		columnsBuffer.append("amount=").append(getAmount()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		return columnsBuffer.toString();
	}
}
