/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.util.Date;


/**
 * @project sqltoy-showcase
 * @version 1.0.0
 * Table: sys_terminal_info   
 */
@Entity(tableName="sys_terminal_info",pk_constraint="PRIMARY")
public abstract class AbstractTerminalInfoVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //terminalCode,terminalId,deviceSn,deviceType,deviceTypeName,posType,deviceOwner,activedDeviceType,saleChannel,deviceDrawMethod,deviceCategory,openTime,closeTime,updateTime,shopId,merchantId,merchantCode,termClass,isActive,activeTime,isTouch,signOrg,branchOrganId,maintainName,maintainCode,maintainOrg,serviceOrg,developPart,developId,status,productClass,mccCode,mccType
	 
	 //not null properties
	 //terminalCode

	/**
	 * 
	 */
	private static final long serialVersionUID = 5360964956136485094L;
	
	/**
	 * terminalID和psam号的混合体
	 */
	@Id(strategy="assign")
	@Column(name="TERMINAL_CODE",length=20L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String terminalCode;
	
	@Column(name="TERMINAL_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String terminalId;
	
	@Column(name="DEVICE_SN",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String deviceSn;
	
	@Column(name="DEVICE_TYPE",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer deviceType;
	
	@Column(name="DEVICE_TYPE_NAME",length=50L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String deviceTypeName;
	
	@Column(name="POS_TYPE",length=10L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String posType;
	
	@Column(name="DEVICE_OWNER",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer deviceOwner;
	
	@Column(name="ACTIVED_DEVICE_TYPE",length=30L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String activedDeviceType;
	
	@Column(name="SALE_CHANNEL",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String saleChannel;
	
	@Column(name="DEVICE_DRAW_METHOD",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer deviceDrawMethod;
	
	@Column(name="DEVICE_CATEGORY",length=10L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String deviceCategory;
	
	@Column(name="OPEN_TIME",length=10L,type=java.sql.Types.DATE,nullable=true)
	protected Date openTime;
	
	@Column(name="CLOSE_TIME",length=10L,type=java.sql.Types.DATE,nullable=true)
	protected Date closeTime;
	
	@Column(name="UPDATE_TIME",length=10L,type=java.sql.Types.DATE,nullable=true)
	protected Date updateTime;
	
	@Column(name="SHOP_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String shopId;
	
	@Column(name="MERCHANT_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String merchantId;
	
	@Column(name="MERCHANT_CODE",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String merchantCode;
	
	/**
	 * 终端大类MPOS/POS
	 */
	@Column(name="TERM_CLASS",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String termClass;
	
	@Column(name="IS_ACTIVE",length=1L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String isActive;
	
	@Column(name="ACTIVE_TIME",length=10L,type=java.sql.Types.DATE,nullable=true)
	protected Date activeTime;
	
	@Column(name="IS_TOUCH",length=1L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String isTouch;
	
	@Column(name="SIGN_ORG",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String signOrg;
	
	@Column(name="BRANCH_ORGAN_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String branchOrganId;
	
	/**
	 * MPOS落维护方对应机构,POS则落签约机构
	 */
	@Column(name="MAINTAIN_NAME",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String maintainName;
	
	/**
	 * MPOS落维护方对应机构,POS则落签约机构
	 */
	@Column(name="MAINTAIN_CODE",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String maintainCode;
	
	/**
	 * MPOS落维护方对应机构,POS则落签约机构
	 */
	@Column(name="MAINTAIN_ORG",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String maintainOrg;
	
	@Column(name="SERVICE_ORG",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String serviceOrg;
	
	@Column(name="DEVELOP_PART",length=10L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer developPart;
	
	@Column(name="DEVELOP_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String developId;
	
	@Column(name="STATUS",length=20L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String status;
	
	@Column(name="PRODUCT_CLASS",length=10L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String productClass;
	
	@Column(name="MCC_CODE",length=10L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String mccCode;
	
	@Column(name="MCC_TYPE",length=5L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String mccType;
	


	/** default constructor */
	public AbstractTerminalInfoVO() {
	}
	
	/** pk constructor */
	public AbstractTerminalInfoVO(String terminalCode)
	{
		this.terminalCode=terminalCode;
	}


	/** full constructor */
	public AbstractTerminalInfoVO(String terminalCode,String terminalId,String deviceSn,Integer deviceType,String deviceTypeName,String posType,Integer deviceOwner,String activedDeviceType,String saleChannel,Integer deviceDrawMethod,String deviceCategory,Date openTime,Date closeTime,Date updateTime,String shopId,String merchantId,String merchantCode,String termClass,String isActive,Date activeTime,String isTouch,String signOrg,String branchOrganId,String maintainName,String maintainCode,String maintainOrg,String serviceOrg,Integer developPart,String developId,String status,String productClass,String mccCode,String mccType)
	{
		this.terminalCode=terminalCode;
		this.terminalId=terminalId;
		this.deviceSn=deviceSn;
		this.deviceType=deviceType;
		this.deviceTypeName=deviceTypeName;
		this.posType=posType;
		this.deviceOwner=deviceOwner;
		this.activedDeviceType=activedDeviceType;
		this.saleChannel=saleChannel;
		this.deviceDrawMethod=deviceDrawMethod;
		this.deviceCategory=deviceCategory;
		this.openTime=openTime;
		this.closeTime=closeTime;
		this.updateTime=updateTime;
		this.shopId=shopId;
		this.merchantId=merchantId;
		this.merchantCode=merchantCode;
		this.termClass=termClass;
		this.isActive=isActive;
		this.activeTime=activeTime;
		this.isTouch=isTouch;
		this.signOrg=signOrg;
		this.branchOrganId=branchOrganId;
		this.maintainName=maintainName;
		this.maintainCode=maintainCode;
		this.maintainOrg=maintainOrg;
		this.serviceOrg=serviceOrg;
		this.developPart=developPart;
		this.developId=developId;
		this.status=status;
		this.productClass=productClass;
		this.mccCode=mccCode;
		this.mccType=mccType;
	}
	
	/**
	 *@param terminalCode the terminalCode to set
	 */
	public void setTerminalCode(String terminalCode) {
		this.terminalCode=terminalCode;
	}
		
	/**
	 *@return the TerminalCode
	 */
	public String getTerminalCode() {
	    return this.terminalCode;
	}
	
	/**
	 *@param terminalId the terminalId to set
	 */
	public void setTerminalId(String terminalId) {
		this.terminalId=terminalId;
	}
		
	/**
	 *@return the TerminalId
	 */
	public String getTerminalId() {
	    return this.terminalId;
	}
	
	/**
	 *@param deviceSn the deviceSn to set
	 */
	public void setDeviceSn(String deviceSn) {
		this.deviceSn=deviceSn;
	}
		
	/**
	 *@return the DeviceSn
	 */
	public String getDeviceSn() {
	    return this.deviceSn;
	}
	
	/**
	 *@param deviceType the deviceType to set
	 */
	public void setDeviceType(Integer deviceType) {
		this.deviceType=deviceType;
	}
		
	/**
	 *@return the DeviceType
	 */
	public Integer getDeviceType() {
	    return this.deviceType;
	}
	
	/**
	 *@param deviceTypeName the deviceTypeName to set
	 */
	public void setDeviceTypeName(String deviceTypeName) {
		this.deviceTypeName=deviceTypeName;
	}
		
	/**
	 *@return the DeviceTypeName
	 */
	public String getDeviceTypeName() {
	    return this.deviceTypeName;
	}
	
	/**
	 *@param posType the posType to set
	 */
	public void setPosType(String posType) {
		this.posType=posType;
	}
		
	/**
	 *@return the PosType
	 */
	public String getPosType() {
	    return this.posType;
	}
	
	/**
	 *@param deviceOwner the deviceOwner to set
	 */
	public void setDeviceOwner(Integer deviceOwner) {
		this.deviceOwner=deviceOwner;
	}
		
	/**
	 *@return the DeviceOwner
	 */
	public Integer getDeviceOwner() {
	    return this.deviceOwner;
	}
	
	/**
	 *@param activedDeviceType the activedDeviceType to set
	 */
	public void setActivedDeviceType(String activedDeviceType) {
		this.activedDeviceType=activedDeviceType;
	}
		
	/**
	 *@return the ActivedDeviceType
	 */
	public String getActivedDeviceType() {
	    return this.activedDeviceType;
	}
	
	/**
	 *@param saleChannel the saleChannel to set
	 */
	public void setSaleChannel(String saleChannel) {
		this.saleChannel=saleChannel;
	}
		
	/**
	 *@return the SaleChannel
	 */
	public String getSaleChannel() {
	    return this.saleChannel;
	}
	
	/**
	 *@param deviceDrawMethod the deviceDrawMethod to set
	 */
	public void setDeviceDrawMethod(Integer deviceDrawMethod) {
		this.deviceDrawMethod=deviceDrawMethod;
	}
		
	/**
	 *@return the DeviceDrawMethod
	 */
	public Integer getDeviceDrawMethod() {
	    return this.deviceDrawMethod;
	}
	
	/**
	 *@param deviceCategory the deviceCategory to set
	 */
	public void setDeviceCategory(String deviceCategory) {
		this.deviceCategory=deviceCategory;
	}
		
	/**
	 *@return the DeviceCategory
	 */
	public String getDeviceCategory() {
	    return this.deviceCategory;
	}
	
	/**
	 *@param openTime the openTime to set
	 */
	public void setOpenTime(Date openTime) {
		this.openTime=openTime;
	}
		
	/**
	 *@return the OpenTime
	 */
	public Date getOpenTime() {
	    return this.openTime;
	}
	
	/**
	 *@param closeTime the closeTime to set
	 */
	public void setCloseTime(Date closeTime) {
		this.closeTime=closeTime;
	}
		
	/**
	 *@return the CloseTime
	 */
	public Date getCloseTime() {
	    return this.closeTime;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public Date getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param shopId the shopId to set
	 */
	public void setShopId(String shopId) {
		this.shopId=shopId;
	}
		
	/**
	 *@return the ShopId
	 */
	public String getShopId() {
	    return this.shopId;
	}
	
	/**
	 *@param merchantId the merchantId to set
	 */
	public void setMerchantId(String merchantId) {
		this.merchantId=merchantId;
	}
		
	/**
	 *@return the MerchantId
	 */
	public String getMerchantId() {
	    return this.merchantId;
	}
	
	/**
	 *@param merchantCode the merchantCode to set
	 */
	public void setMerchantCode(String merchantCode) {
		this.merchantCode=merchantCode;
	}
		
	/**
	 *@return the MerchantCode
	 */
	public String getMerchantCode() {
	    return this.merchantCode;
	}
	
	/**
	 *@param termClass the termClass to set
	 */
	public void setTermClass(String termClass) {
		this.termClass=termClass;
	}
		
	/**
	 *@return the TermClass
	 */
	public String getTermClass() {
	    return this.termClass;
	}
	
	/**
	 *@param isActive the isActive to set
	 */
	public void setIsActive(String isActive) {
		this.isActive=isActive;
	}
		
	/**
	 *@return the IsActive
	 */
	public String getIsActive() {
	    return this.isActive;
	}
	
	/**
	 *@param activeTime the activeTime to set
	 */
	public void setActiveTime(Date activeTime) {
		this.activeTime=activeTime;
	}
		
	/**
	 *@return the ActiveTime
	 */
	public Date getActiveTime() {
	    return this.activeTime;
	}
	
	/**
	 *@param isTouch the isTouch to set
	 */
	public void setIsTouch(String isTouch) {
		this.isTouch=isTouch;
	}
		
	/**
	 *@return the IsTouch
	 */
	public String getIsTouch() {
	    return this.isTouch;
	}
	
	/**
	 *@param signOrg the signOrg to set
	 */
	public void setSignOrg(String signOrg) {
		this.signOrg=signOrg;
	}
		
	/**
	 *@return the SignOrg
	 */
	public String getSignOrg() {
	    return this.signOrg;
	}
	
	/**
	 *@param branchOrganId the branchOrganId to set
	 */
	public void setBranchOrganId(String branchOrganId) {
		this.branchOrganId=branchOrganId;
	}
		
	/**
	 *@return the BranchOrganId
	 */
	public String getBranchOrganId() {
	    return this.branchOrganId;
	}
	
	/**
	 *@param maintainName the maintainName to set
	 */
	public void setMaintainName(String maintainName) {
		this.maintainName=maintainName;
	}
		
	/**
	 *@return the MaintainName
	 */
	public String getMaintainName() {
	    return this.maintainName;
	}
	
	/**
	 *@param maintainCode the maintainCode to set
	 */
	public void setMaintainCode(String maintainCode) {
		this.maintainCode=maintainCode;
	}
		
	/**
	 *@return the MaintainCode
	 */
	public String getMaintainCode() {
	    return this.maintainCode;
	}
	
	/**
	 *@param maintainOrg the maintainOrg to set
	 */
	public void setMaintainOrg(String maintainOrg) {
		this.maintainOrg=maintainOrg;
	}
		
	/**
	 *@return the MaintainOrg
	 */
	public String getMaintainOrg() {
	    return this.maintainOrg;
	}
	
	/**
	 *@param serviceOrg the serviceOrg to set
	 */
	public void setServiceOrg(String serviceOrg) {
		this.serviceOrg=serviceOrg;
	}
		
	/**
	 *@return the ServiceOrg
	 */
	public String getServiceOrg() {
	    return this.serviceOrg;
	}
	
	/**
	 *@param developPart the developPart to set
	 */
	public void setDevelopPart(Integer developPart) {
		this.developPart=developPart;
	}
		
	/**
	 *@return the DevelopPart
	 */
	public Integer getDevelopPart() {
	    return this.developPart;
	}
	
	/**
	 *@param developId the developId to set
	 */
	public void setDevelopId(String developId) {
		this.developId=developId;
	}
		
	/**
	 *@return the DevelopId
	 */
	public String getDevelopId() {
	    return this.developId;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(String status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public String getStatus() {
	    return this.status;
	}
	
	/**
	 *@param productClass the productClass to set
	 */
	public void setProductClass(String productClass) {
		this.productClass=productClass;
	}
		
	/**
	 *@return the ProductClass
	 */
	public String getProductClass() {
	    return this.productClass;
	}
	
	/**
	 *@param mccCode the mccCode to set
	 */
	public void setMccCode(String mccCode) {
		this.mccCode=mccCode;
	}
		
	/**
	 *@return the MccCode
	 */
	public String getMccCode() {
	    return this.mccCode;
	}
	
	/**
	 *@param mccType the mccType to set
	 */
	public void setMccType(String mccType) {
		this.mccType=mccType;
	}
		
	/**
	 *@return the MccType
	 */
	public String getMccType() {
	    return this.mccType;
	}



	/**
     * @todo vo columns to String
     */
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("terminalCode=").append(getTerminalCode()).append("\n");
		columnsBuffer.append("terminalId=").append(getTerminalId()).append("\n");
		columnsBuffer.append("deviceSn=").append(getDeviceSn()).append("\n");
		columnsBuffer.append("deviceType=").append(getDeviceType()).append("\n");
		columnsBuffer.append("deviceTypeName=").append(getDeviceTypeName()).append("\n");
		columnsBuffer.append("posType=").append(getPosType()).append("\n");
		columnsBuffer.append("deviceOwner=").append(getDeviceOwner()).append("\n");
		columnsBuffer.append("activedDeviceType=").append(getActivedDeviceType()).append("\n");
		columnsBuffer.append("saleChannel=").append(getSaleChannel()).append("\n");
		columnsBuffer.append("deviceDrawMethod=").append(getDeviceDrawMethod()).append("\n");
		columnsBuffer.append("deviceCategory=").append(getDeviceCategory()).append("\n");
		columnsBuffer.append("openTime=").append(getOpenTime()).append("\n");
		columnsBuffer.append("closeTime=").append(getCloseTime()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		columnsBuffer.append("shopId=").append(getShopId()).append("\n");
		columnsBuffer.append("merchantId=").append(getMerchantId()).append("\n");
		columnsBuffer.append("merchantCode=").append(getMerchantCode()).append("\n");
		columnsBuffer.append("termClass=").append(getTermClass()).append("\n");
		columnsBuffer.append("isActive=").append(getIsActive()).append("\n");
		columnsBuffer.append("activeTime=").append(getActiveTime()).append("\n");
		columnsBuffer.append("isTouch=").append(getIsTouch()).append("\n");
		columnsBuffer.append("signOrg=").append(getSignOrg()).append("\n");
		columnsBuffer.append("branchOrganId=").append(getBranchOrganId()).append("\n");
		columnsBuffer.append("maintainName=").append(getMaintainName()).append("\n");
		columnsBuffer.append("maintainCode=").append(getMaintainCode()).append("\n");
		columnsBuffer.append("maintainOrg=").append(getMaintainOrg()).append("\n");
		columnsBuffer.append("serviceOrg=").append(getServiceOrg()).append("\n");
		columnsBuffer.append("developPart=").append(getDevelopPart()).append("\n");
		columnsBuffer.append("developId=").append(getDevelopId()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		columnsBuffer.append("productClass=").append(getProductClass()).append("\n");
		columnsBuffer.append("mccCode=").append(getMccCode()).append("\n");
		columnsBuffer.append("mccType=").append(getMccType()).append("\n");
		return columnsBuffer.toString();
	}
}
