/**
 *@Generated by sagacity-quickvo 4.0
 */
package sqltoy.showcase.system.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.util.Date;


/**
 * @project sqltoy-showcase
 * @version 1.0.0
 * Table: sys_organ_info,Remark:机构信息表   
 */
@Entity(tableName="sys_organ_info",pk_constraint="PRIMARY")
public abstract class AbstractOrganInfoVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //organId,organName,aliasName,organCode,organPid,nodeRoute,nodeLevel,isLeaf,operator,operateDate,status
	 
	 //not null properties
	 //organId,organName,operator,operateDate,status

	/**
	 * 
	 */
	private static final long serialVersionUID = 5263877058284922339L;
	
	/**
	 * 机构编号
	 */
	@Id(strategy="generator",generator="org.sagacity.sqltoy.plugin.id.DefaultIdGenerator")
	@Column(name="ORGAN_ID",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String organId;
	
	/**
	 * 机构名称
	 */
	@Column(name="ORGAN_NAME",length=100L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String organName;
	
	/**
	 * 机构简称
	 */
	@Column(name="ALIAS_NAME",length=100L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String aliasName;
	
	/**
	 * 机构代码
	 */
	@Column(name="ORGAN_CODE",length=60L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String organCode;
	
	/**
	 * 上级机构
	 */
	@Column(name="ORGAN_PID",length=22L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String organPid;
	
	/**
	 * 节点路径
	 */
	@Column(name="NODE_ROUTE",length=220L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String nodeRoute;
	
	/**
	 * 节点层级
	 */
	@Column(name="NODE_LEVEL",length=2L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer nodeLevel;
	
	/**
	 * 是否叶子节点
	 */
	@Column(name="IS_LEAF",length=1L,type=java.sql.Types.INTEGER,nullable=true)
	protected Integer isLeaf;
	
	/**
	 * 操作人
	 */
	@Column(name="OPERATOR",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String operator;
	
	/**
	 * 操作日期
	 */
	@Column(name="OPERATE_DATE",length=10L,type=java.sql.Types.DATE,nullable=false)
	protected Date operateDate;
	
	/**
	 * 启用标志
	 */
	@Column(name="STATUS",length=1L,defaultValue="1",type=java.sql.Types.CHAR,nullable=false)
	protected String status;
	


	/** default constructor */
	public AbstractOrganInfoVO() {
	}
	
	/** pk constructor */
	public AbstractOrganInfoVO(String organId)
	{
		this.organId=organId;
	}

	/** minimal constructor */
	public AbstractOrganInfoVO(String organId,String organName,String operator,Date operateDate,String status)
	{
		this.organId=organId;
		this.organName=organName;
		this.operator=operator;
		this.operateDate=operateDate;
		this.status=status;
	}

	/** full constructor */
	public AbstractOrganInfoVO(String organId,String organName,String aliasName,String organCode,String organPid,String nodeRoute,Integer nodeLevel,Integer isLeaf,String operator,Date operateDate,String status)
	{
		this.organId=organId;
		this.organName=organName;
		this.aliasName=aliasName;
		this.organCode=organCode;
		this.organPid=organPid;
		this.nodeRoute=nodeRoute;
		this.nodeLevel=nodeLevel;
		this.isLeaf=isLeaf;
		this.operator=operator;
		this.operateDate=operateDate;
		this.status=status;
	}
	
	/**
	 *@param organId the organId to set
	 */
	public void setOrganId(String organId) {
		this.organId=organId;
	}
		
	/**
	 *@return the OrganId
	 */
	public String getOrganId() {
	    return this.organId;
	}
	
	/**
	 *@param organName the organName to set
	 */
	public void setOrganName(String organName) {
		this.organName=organName;
	}
		
	/**
	 *@return the OrganName
	 */
	public String getOrganName() {
	    return this.organName;
	}
	
	/**
	 *@param aliasName the aliasName to set
	 */
	public void setAliasName(String aliasName) {
		this.aliasName=aliasName;
	}
		
	/**
	 *@return the AliasName
	 */
	public String getAliasName() {
	    return this.aliasName;
	}
	
	/**
	 *@param organCode the organCode to set
	 */
	public void setOrganCode(String organCode) {
		this.organCode=organCode;
	}
		
	/**
	 *@return the OrganCode
	 */
	public String getOrganCode() {
	    return this.organCode;
	}
	
	/**
	 *@param organPid the organPid to set
	 */
	public void setOrganPid(String organPid) {
		this.organPid=organPid;
	}
		
	/**
	 *@return the OrganPid
	 */
	public String getOrganPid() {
	    return this.organPid;
	}
	
	/**
	 *@param nodeRoute the nodeRoute to set
	 */
	public void setNodeRoute(String nodeRoute) {
		this.nodeRoute=nodeRoute;
	}
		
	/**
	 *@return the NodeRoute
	 */
	public String getNodeRoute() {
	    return this.nodeRoute;
	}
	
	/**
	 *@param nodeLevel the nodeLevel to set
	 */
	public void setNodeLevel(Integer nodeLevel) {
		this.nodeLevel=nodeLevel;
	}
		
	/**
	 *@return the NodeLevel
	 */
	public Integer getNodeLevel() {
	    return this.nodeLevel;
	}
	
	/**
	 *@param isLeaf the isLeaf to set
	 */
	public void setIsLeaf(Integer isLeaf) {
		this.isLeaf=isLeaf;
	}
		
	/**
	 *@return the IsLeaf
	 */
	public Integer getIsLeaf() {
	    return this.isLeaf;
	}
	
	/**
	 *@param operator the operator to set
	 */
	public void setOperator(String operator) {
		this.operator=operator;
	}
		
	/**
	 *@return the Operator
	 */
	public String getOperator() {
	    return this.operator;
	}
	
	/**
	 *@param operateDate the operateDate to set
	 */
	public void setOperateDate(Date operateDate) {
		this.operateDate=operateDate;
	}
		
	/**
	 *@return the OperateDate
	 */
	public Date getOperateDate() {
	    return this.operateDate;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(String status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public String getStatus() {
	    return this.status;
	}



	/**
     * @todo vo columns to String
     */
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("organId=").append(getOrganId()).append("\n");
		columnsBuffer.append("organName=").append(getOrganName()).append("\n");
		columnsBuffer.append("aliasName=").append(getAliasName()).append("\n");
		columnsBuffer.append("organCode=").append(getOrganCode()).append("\n");
		columnsBuffer.append("organPid=").append(getOrganPid()).append("\n");
		columnsBuffer.append("nodeRoute=").append(getNodeRoute()).append("\n");
		columnsBuffer.append("nodeLevel=").append(getNodeLevel()).append("\n");
		columnsBuffer.append("isLeaf=").append(getIsLeaf()).append("\n");
		columnsBuffer.append("operator=").append(getOperator()).append("\n");
		columnsBuffer.append("operateDate=").append(getOperateDate()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		return columnsBuffer.toString();
	}
}
