/**
 *@Generated by sagacity-quickvo 4.13
 */
package org.sagacity.sqltoy.demo.domain;

import java.time.LocalDate;

import org.sagacity.sqltoy.config.annotation.Index;
import org.sagacity.sqltoy.config.annotation.Indexes;
import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import org.sagacity.sqltoy.demo.domain.base.AbstractStaffInfo;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0 Table: sqltoy_staff_info,Remark:员工信息表
 */
@SqlToyEntity
@Indexes(indexes = { @Index(isUnique = true, name = "", columns = {}, sortTypes = {}),
		@Index(isUnique = true, name = "", columns = {}, sortTypes = {}) })
public class StaffInfo extends AbstractStaffInfo {
	/**
	 * 
	 */
	private static final long serialVersionUID = 8872936239782687517L;

	/** default constructor */
	public StaffInfo() {
		super();
	}

	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public StaffInfo(String staffId) {
		this.staffId = staffId;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	private LocalDate beginDate;

	private LocalDate endDate;

	/**
	 * 机构名称
	 */
	private String organName;

	/**
	 * 性别名称
	 */
	private String sexTypeName;

	/**
	 * @todo vo columns to String
	 */
	@Override
	public String toString() {
		return super.toString();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public StaffInfo clone() {
		try {
			return (StaffInfo) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}

	public String getOrganName() {
		return organName;
	}

	public void setOrganName(String organName) {
		this.organName = organName;
	}

	public String getSexTypeName() {
		return sexTypeName;
	}

	public void setSexTypeName(String sexTypeName) {
		this.sexTypeName = sexTypeName;
	}

	public LocalDate getBeginDate() {
		return beginDate;
	}

	public void setBeginDate(LocalDate beginDate) {
		this.beginDate = beginDate;
	}

	public LocalDate getEndDate() {
		return endDate;
	}

	public void setEndDate(LocalDate endDate) {
		this.endDate = endDate;
	}

}
