/**
 *@Generated by QuickVO Tools 1.5 
 */
package org.sagacity.sqltoy.demo.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import org.sagacity.sqltoy.demo.vo.base.AbstractStaffGroupVO;

/**
 * @project sqltoy-orm
 * @author chenrenfei@lakala.com
 * @version 1.0.0
 * 员工技能组  		
 * StaffGroupVO generated by SYS_STAFF_GROUP
 */
@SqlToyEntity
public class StaffGroupVO extends AbstractStaffGroupVO {	
	/** default constructor */
	public StaffGroupVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public StaffGroupVO(String staffId,String groupId)
	{
		this.staffId=staffId;
		this.groupId=groupId;
	}

	/** minimal constructor */
	public StaffGroupVO(String staffId,String groupId,Integer isMajor)
	{
		this.staffId=staffId;
		this.groupId=groupId;
		this.isMajor=isMajor;
	}

	/** full constructor */
	public StaffGroupVO(String staffId,String groupId,Integer techLevel,Integer isMajor)
	{
		this.staffId=staffId;
		this.groupId=groupId;
		this.techLevel=techLevel;
		this.isMajor=isMajor;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public StaffGroupVO clone() {
		try {
			// TODO Auto-generated method stub
			return (StaffGroupVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
