/**
 *@Generated by sagacity-quickvo 4.0
 */
package ${quickVO.daoPackage};

import org.springframework.stereotype.Repository;
import org.sagacity.sqltoy.support.BaseDaoSupport;
import ${quickVO.voPackage}.${quickVO.voName};
<#if (quickVO.type=='view')>
import org.sagacity.sqltoy.model.PaginationModel;
</#if>

/**
 * @project <#if (quickVO.projectName?exists)>${quickVO.projectName}</#if>
 * @description <p>CRUD about table of ${quickVO.tableName}<#if (quickVO.tableRemark?exists && quickVO.tableRemark!='')>(${quickVO.tableRemark})</#if></p>
 * @author <#if (quickVO.author?exists)>${quickVO.author}</#if>
 * @version <#if (quickVO.version?exists)>${quickVO.version}</#if>
 * @date ${quickVO.dateTime}
 */
@Repository("${quickVO.daoName?uncap_first}")
public class ${quickVO.daoName} extends BaseDaoSupport {	
	//friendly reminder(常用操作友情提示)
	//分页查询：PaginationModel super.findPageBySql(PaginationModel pageModel,String sqlId,String[] paramsNamed,Object[] paramValues, Class ${quickVO.voName?uncap_first}Class);
	//一般查询：List super.findBySql(String sqlOrNamedSql,String[] paramsNamed,Object[] paramsValue,Class ${quickVO.voName?uncap_first}Class);
		
	<#if (quickVO.type=='view')>
	/**
	 *@todo 分页查询视图${quickVO.tableName} 中的记录
	 */
	public PaginationModel findPage(PaginationModel pageModel,${quickVO.voName} ${quickVO.voName?uncap_first}) throws Exception{
		return super.findPageBySql(pageModel,"sqlId",${quickVO.voName?uncap_first});
	}
	</#if>
}