/**
 *@Generated by QuickVO Tools 1.5 
 */
package org.sagacity.sqltoy.demo.vo;

import java.sql.Timestamp;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import org.sagacity.sqltoy.demo.vo.base.AbstractDictDetailVO;

/**
 * @project sqltoy-orm
 * @author chenrenfei@lakala.com
 * @version 1.0.0
 * 数据字典明细表  		
 * DictDetailVO generated by TEST_DICT_DETAIL
 */
@SqlToyEntity
public class DictDetailVO extends AbstractDictDetailVO {	
	/** default constructor */
	public DictDetailVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public DictDetailVO(String dictTypeCode,String dictKey)
	{
		this.dictTypeCode=dictTypeCode;
		this.dictKey=dictKey;
	}

	/** minimal constructor */
	public DictDetailVO(String dictTypeCode,String dictKey,String dictName,Integer showIndex,Timestamp lastUpdate,Integer enabled)
	{
		this.dictTypeCode=dictTypeCode;
		this.dictKey=dictKey;
		this.dictName=dictName;
		this.showIndex=showIndex;
		this.lastUpdate=lastUpdate;
		this.enabled=enabled;
	}

	/** full constructor */
	public DictDetailVO(String dictTypeCode,String dictKey,String dictName,String dictNameEn,Integer showIndex,Timestamp lastUpdate,String comments,String segment,Integer enabled)
	{
		this.dictTypeCode=dictTypeCode;
		this.dictKey=dictKey;
		this.dictName=dictName;
		this.dictNameEn=dictNameEn;
		this.showIndex=showIndex;
		this.lastUpdate=lastUpdate;
		this.comments=comments;
		this.segment=segment;
		this.enabled=enabled;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public DictDetailVO clone() {
		try {
			// TODO Auto-generated method stub
			return (DictDetailVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
