/**
 *@Generated by sagacity-quickvo 4.0
 */
package org.sagacity.sqltoy.showcase.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.math.BigDecimal;
import org.sagacity.sqltoy.showcase.vo.base.AbstractAreaInfoVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_area_info,Remark:地区代码表 	
 */
@SqlToyEntity
public class AreaInfoVO extends AbstractAreaInfoVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 5722033876401160663L;
	
	/**
	 * 请绝对不要在此类中重复定义Abstract类中的对应表字段的属性,易导致属性失去@Column关联表字段的注解特征,无法正确生成相应的sql
	 * 如覆盖定义了属性C,原本生成 insert into tableName (A,B,C) values(?,?,?) 变成了 insert into tableName (A,B) values(?,?)
	 */
	 
	/** default constructor */
	public AreaInfoVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public AreaInfoVO(String areaCode)
	{
		this.areaCode=areaCode;
	}

	/** minimal constructor */
	public AreaInfoVO(String areaCode,String areaName,String areaPid,String nodeRoute,Integer nodeLevel,Integer isLeaf,Integer showIndex,Integer status)
	{
		this.areaCode=areaCode;
		this.areaName=areaName;
		this.areaPid=areaPid;
		this.nodeRoute=nodeRoute;
		this.nodeLevel=nodeLevel;
		this.isLeaf=isLeaf;
		this.showIndex=showIndex;
		this.status=status;
	}

	/** full constructor */
	public AreaInfoVO(String areaCode,String areaName,String areaTel,String areaPid,String englishName,String initial,String countryCode,String cityCode,String cityName,String provinceCode,String provinceName,String fullName,BigDecimal longitude,BigDecimal latitude,String nodeRoute,Integer nodeLevel,Integer isLeaf,Integer showIndex,Integer status)
	{
		this.areaCode=areaCode;
		this.areaName=areaName;
		this.areaTel=areaTel;
		this.areaPid=areaPid;
		this.englishName=englishName;
		this.initial=initial;
		this.countryCode=countryCode;
		this.cityCode=cityCode;
		this.cityName=cityName;
		this.provinceCode=provinceCode;
		this.provinceName=provinceName;
		this.fullName=fullName;
		this.longitude=longitude;
		this.latitude=latitude;
		this.nodeRoute=nodeRoute;
		this.nodeLevel=nodeLevel;
		this.isLeaf=isLeaf;
		this.showIndex=showIndex;
		this.status=status;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	
	//请绝对不要在此类中重复定义Abstract类中的对应表字段的属性,易导致属性失去@Column关联表字段的注解特征,无法正确生成相应的sql
	//如覆盖定义了属性C,原本生成 insert into tableName (A,B,C) values(?,?,?) 变成了 insert into tableName (A,B) values(?,?)
	 
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public AreaInfoVO clone() {
		try {
			// TODO Auto-generated method stub
			return (AreaInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
