/**
 *@Generated by sagacity-quickvo 4.0
 */
package org.sagacity.sqltoy.showcase.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.math.BigDecimal;
import java.util.Date;
import org.sagacity.sqltoy.showcase.vo.base.AbstractDeviceOrderInfoVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_device_order_info,Remark:硬件购销定单表(演示有规则单号) 	
 */
@SqlToyEntity
public class DeviceOrderInfoVO extends AbstractDeviceOrderInfoVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2588208747442430243L;
	
	/**
	 * 请绝对不要在此类中重复定义Abstract类中的对应表字段的属性,易导致属性失去@Column关联表字段的注解特征,无法正确生成相应的sql
	 * 如覆盖定义了属性C,原本生成 insert into tableName (A,B,C) values(?,?,?) 变成了 insert into tableName (A,B) values(?,?)
	 */
	 
	/** default constructor */
	public DeviceOrderInfoVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public DeviceOrderInfoVO(String orderId)
	{
		this.orderId=orderId;
	}

	/** minimal constructor */
	public DeviceOrderInfoVO(String orderId,String deviceType,String psType,Date transDate,String createBy,Date createTime,String updateBy,Date updateTime,Integer status)
	{
		this.orderId=orderId;
		this.deviceType=deviceType;
		this.psType=psType;
		this.transDate=transDate;
		this.createBy=createBy;
		this.createTime=createTime;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
		this.status=status;
	}

	/** full constructor */
	public DeviceOrderInfoVO(String orderId,String deviceType,String psType,BigDecimal totalCnt,BigDecimal totalAmt,String buyer,String saler,Date transDate,Date deliveryTerm,String staffId,String createBy,Date createTime,String updateBy,Date updateTime,Integer status)
	{
		this.orderId=orderId;
		this.deviceType=deviceType;
		this.psType=psType;
		this.totalCnt=totalCnt;
		this.totalAmt=totalAmt;
		this.buyer=buyer;
		this.saler=saler;
		this.transDate=transDate;
		this.deliveryTerm=deliveryTerm;
		this.staffId=staffId;
		this.createBy=createBy;
		this.createTime=createTime;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
		this.status=status;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	
	//请绝对不要在此类中重复定义Abstract类中的对应表字段的属性,易导致属性失去@Column关联表字段的注解特征,无法正确生成相应的sql
	//如覆盖定义了属性C,原本生成 insert into tableName (A,B,C) values(?,?,?) 变成了 insert into tableName (A,B) values(?,?)
	 
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public DeviceOrderInfoVO clone() {
		try {
			// TODO Auto-generated method stub
			return (DeviceOrderInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
