/**
 *@Generated by sagacity-quickvo 4.0
 */
package org.sagacity.sqltoy.showcase.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import org.sagacity.sqltoy.showcase.vo.base.AbstractUserLogVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_user_log,Remark:用户日志表 	
 */
@SqlToyEntity
public class UserLogVO extends AbstractUserLogVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4041499313163417551L;
	
	/** default constructor */
	public UserLogVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public UserLogVO(String logId)
	{
		this.logId=logId;
	}

	/** minimal constructor */
	public UserLogVO(String logId,String userId,Date logTime,Date logDate,String logType,String channel,String contents)
	{
		this.logId=logId;
		this.userId=userId;
		this.logTime=logTime;
		this.logDate=logDate;
		this.logType=logType;
		this.channel=channel;
		this.contents=contents;
	}

	/** full constructor */
	public UserLogVO(String logId,String userId,String terminalIp,String deviceCode,Date logTime,Date logDate,String logType,String channel,String contents)
	{
		this.logId=logId;
		this.userId=userId;
		this.terminalIp=terminalIp;
		this.deviceCode=deviceCode;
		this.logTime=logTime;
		this.logDate=logDate;
		this.logType=logType;
		this.channel=channel;
		this.contents=contents;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public UserLogVO clone() {
		try {
			// TODO Auto-generated method stub
			return (UserLogVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
