/**
 *@Generated by sagacity-quickvo 4.0
 */
package com.sagframe.sqltoy.showcase.vo;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sagframe.sqltoy.showcase.vo.base.AbstractComplexpkItemVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_complexpk_item,Remark:复合主键级联操作子表 	
 */
@SqlToyEntity
public class ComplexpkItemVO extends AbstractComplexpkItemVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 607037834586769345L;
	
	/** default constructor */
	public ComplexpkItemVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public ComplexpkItemVO(String id)
	{
		this.id=id;
	}

	/** minimal constructor */
	public ComplexpkItemVO(String id,String productId,BigDecimal quantity,BigDecimal price,BigDecimal amt,LocalDateTime createTime)
	{
		this.id=id;
		this.productId=productId;
		this.quantity=quantity;
		this.price=price;
		this.amt=amt;
		this.createTime=createTime;
	}

	/** full constructor */
	public ComplexpkItemVO(String id,LocalDate transDate,String transCode,String productId,BigDecimal quantity,BigDecimal price,BigDecimal amt,LocalDateTime createTime)
	{
		this.id=id;
		this.transDate=transDate;
		this.transCode=transCode;
		this.productId=productId;
		this.quantity=quantity;
		this.price=price;
		this.amt=amt;
		this.createTime=createTime;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public ComplexpkItemVO clone() {
		try {
			// TODO Auto-generated method stub
			return (ComplexpkItemVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
