/**
 *@Generated by sagacity-quickvo 4.6
 */
package com.sagframe.sqltoy.showcase.vo;

import java.math.BigDecimal;
import java.sql.Timestamp;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sagframe.sqltoy.showcase.vo.base.AbstractSequenceTableVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: SQLTOY_SEQUENCE_TABLE,Remark:单SEQUENCE主键验证表 	
 */
@SqlToyEntity
public class SequenceTableVO extends AbstractSequenceTableVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6901115804847477600L;
	
	/** default constructor */
	public SequenceTableVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public SequenceTableVO(BigDecimal id)
	{
		this.id=id;
	}


	/** full constructor */
	public SequenceTableVO(BigDecimal id,String name,Timestamp createTime)
	{
		this.id=id;
		this.name=name;
		this.createTime=createTime;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public SequenceTableVO clone() {
		try {
			return (SequenceTableVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
