/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import sqltoy.showcase.system.vo.base.AbstractCardappInfoVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sys_cardapp_info 	
 */
@SqlToyEntity
public class CardappInfoVO extends AbstractCardappInfoVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2504171113332237742L;
	
	/** default constructor */
	public CardappInfoVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public CardappInfoVO(Integer cardappId)
	{
		this.cardappId=cardappId;
	}


	/** full constructor */
	public CardappInfoVO(Integer cardappId,Integer terminalId,Integer cardAppType,String merchantCode,String termNo,String mccCode,String mccType,Integer signOrg,String status,Date createTm,Integer createUser,Date lastModifyTm,Date cardappCloseDate)
	{
		this.cardappId=cardappId;
		this.terminalId=terminalId;
		this.cardAppType=cardAppType;
		this.merchantCode=merchantCode;
		this.termNo=termNo;
		this.mccCode=mccCode;
		this.mccType=mccType;
		this.signOrg=signOrg;
		this.status=status;
		this.createTm=createTm;
		this.createUser=createUser;
		this.lastModifyTm=lastModifyTm;
		this.cardappCloseDate=cardappCloseDate;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public CardappInfoVO clone() {
		try {
			// TODO Auto-generated method stub
			return (CardappInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
