/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import java.util.List;
import sqltoy.showcase.system.vo.base.AbstractMultpkMainVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * 复合主键关联主表  		
 * MultpkMainVO generated by sys_multpk_main
 */
@SqlToyEntity
public class MultpkMainVO extends AbstractMultpkMainVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3291047102657574796L;
	
	/** default constructor */
	public MultpkMainVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public MultpkMainVO(String bizType,String batchNo)
	{
		this.bizType=bizType;
		this.batchNo=batchNo;
	}


	/** full constructor */
	public MultpkMainVO(String bizType,String batchNo,Double amount,Date createTime)
	{
		this.bizType=bizType;
		this.batchNo=batchNo;
		this.amount=amount;
		this.createTime=createTime;
	}

	/**
	 * mapping sys_multpk_item data to sys_multpk_main oneToMany List
	 */
	public void mappingMultpkItemVOs(List<MultpkMainVO> mainSet,List<MultpkItemVO> itemSet)
    {
    	if(mainSet==null || mainSet.isEmpty() || itemSet==null||itemSet.isEmpty())
    		return;
    	MultpkMainVO main;
    	MultpkItemVO item;
    	for(int i=0;i<mainSet.size();i++){
    		main=mainSet.get(i);
    		if(itemSet.size()==0)
    			break;
    		for(int j=0;j<itemSet.size();j++){
    			item=itemSet.get(j);
    			if(main.getBizType().equals(item.getBizType())&& main.getBatchNo().equals(item.getBatchNo())){
    			  main.multpkItemVOs.add(item);
    			  itemSet.remove(j);
    			  j--;
    			}
    		}
    	}
    }
	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public MultpkMainVO clone() {
		try {
			// TODO Auto-generated method stub
			return (MultpkMainVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
