/**
 *@Generated by sagacity-quickvo 4.0
 */
package sqltoy.showcase.sagacity.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;
import java.sql.Timestamp;


/**
 * @project sqltoy-showcase
 * @version 1.0.0
 * Table: sag_dict_detail,Remark:数据字典明细表   
 */
@Entity(tableName="sag_dict_detail",pk_constraint="PRIMARY")
public abstract class AbstractDictDetailVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //dictTypeCode,dictKey,dictName,showIndex,comments,segment,updateBy,updateTime,status
	 
	 //not null properties
	 //dictTypeCode,dictKey,dictName,showIndex,updateBy,updateTime,status

	/**
	 * 
	 */
	private static final long serialVersionUID = 6986044858001913146L;
	
	/**
	 * 字典类型编码
	 */
	@Id
	@Column(name="DICT_TYPE_CODE",length=50L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String dictTypeCode;
	
	/**
	 * 字典KEY(字典编码)
	 */
	@Id
	@Column(name="DICT_KEY",length=100L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String dictKey;
	
	/**
	 * 字典显示值(显示的名称)
	 */
	@Column(name="DICT_NAME",length=100L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String dictName;
	
	/**
	 * 显示顺序
	 */
	@Column(name="SHOW_INDEX",length=8L,type=java.sql.Types.INTEGER,nullable=false)
	protected Integer showIndex;
	
	/**
	 * 字典描述
	 */
	@Column(name="COMMENTS",length=1000L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String comments;
	
	/**
	 * 附加字段
	 */
	@Column(name="SEGMENT",length=100L,type=java.sql.Types.VARCHAR,nullable=true)
	protected String segment;
	
	/**
	 * 最后修改人
	 */
	@Column(name="UPDATE_BY",length=22L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String updateBy;
	
	/**
	 * 最后修改时间
	 */
	@Column(name="UPDATE_TIME",length=26L,defaultValue="CURRENT_TIMESTAMP",type=java.sql.Types.TIMESTAMP,nullable=false)
	protected Timestamp updateTime;
	
	/**
	 * 启用标志
	 */
	@Column(name="STATUS",length=1L,defaultValue="1",type=java.sql.Types.CHAR,nullable=false)
	protected String status;
	


	/** default constructor */
	public AbstractDictDetailVO() {
	}
	
	/** pk constructor */
	public AbstractDictDetailVO(String dictTypeCode,String dictKey)
	{
		this.dictTypeCode=dictTypeCode;
		this.dictKey=dictKey;
	}

	/** minimal constructor */
	public AbstractDictDetailVO(String dictTypeCode,String dictKey,String dictName,Integer showIndex,String updateBy,Timestamp updateTime,String status)
	{
		this.dictTypeCode=dictTypeCode;
		this.dictKey=dictKey;
		this.dictName=dictName;
		this.showIndex=showIndex;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
		this.status=status;
	}

	/** full constructor */
	public AbstractDictDetailVO(String dictTypeCode,String dictKey,String dictName,Integer showIndex,String comments,String segment,String updateBy,Timestamp updateTime,String status)
	{
		this.dictTypeCode=dictTypeCode;
		this.dictKey=dictKey;
		this.dictName=dictName;
		this.showIndex=showIndex;
		this.comments=comments;
		this.segment=segment;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
		this.status=status;
	}
	
	/**
	 *@param dictTypeCode the dictTypeCode to set
	 */
	public void setDictTypeCode(String dictTypeCode) {
		this.dictTypeCode=dictTypeCode;
	}
		
	/**
	 *@return the DictTypeCode
	 */
	public String getDictTypeCode() {
	    return this.dictTypeCode;
	}
	
	/**
	 *@param dictKey the dictKey to set
	 */
	public void setDictKey(String dictKey) {
		this.dictKey=dictKey;
	}
		
	/**
	 *@return the DictKey
	 */
	public String getDictKey() {
	    return this.dictKey;
	}
	
	/**
	 *@param dictName the dictName to set
	 */
	public void setDictName(String dictName) {
		this.dictName=dictName;
	}
		
	/**
	 *@return the DictName
	 */
	public String getDictName() {
	    return this.dictName;
	}
	
	/**
	 *@param showIndex the showIndex to set
	 */
	public void setShowIndex(Integer showIndex) {
		this.showIndex=showIndex;
	}
		
	/**
	 *@return the ShowIndex
	 */
	public Integer getShowIndex() {
	    return this.showIndex;
	}
	
	/**
	 *@param comments the comments to set
	 */
	public void setComments(String comments) {
		this.comments=comments;
	}
		
	/**
	 *@return the Comments
	 */
	public String getComments() {
	    return this.comments;
	}
	
	/**
	 *@param segment the segment to set
	 */
	public void setSegment(String segment) {
		this.segment=segment;
	}
		
	/**
	 *@return the Segment
	 */
	public String getSegment() {
	    return this.segment;
	}
	
	/**
	 *@param updateBy the updateBy to set
	 */
	public void setUpdateBy(String updateBy) {
		this.updateBy=updateBy;
	}
		
	/**
	 *@return the UpdateBy
	 */
	public String getUpdateBy() {
	    return this.updateBy;
	}
	
	/**
	 *@param updateTime the updateTime to set
	 */
	public void setUpdateTime(Timestamp updateTime) {
		this.updateTime=updateTime;
	}
		
	/**
	 *@return the UpdateTime
	 */
	public Timestamp getUpdateTime() {
	    return this.updateTime;
	}
	
	/**
	 *@param status the status to set
	 */
	public void setStatus(String status) {
		this.status=status;
	}
		
	/**
	 *@return the Status
	 */
	public String getStatus() {
	    return this.status;
	}



	/**
     * @todo vo columns to String
     */
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("dictTypeCode=").append(getDictTypeCode()).append("\n");
		columnsBuffer.append("dictKey=").append(getDictKey()).append("\n");
		columnsBuffer.append("dictName=").append(getDictName()).append("\n");
		columnsBuffer.append("showIndex=").append(getShowIndex()).append("\n");
		columnsBuffer.append("comments=").append(getComments()).append("\n");
		columnsBuffer.append("segment=").append(getSegment()).append("\n");
		columnsBuffer.append("updateBy=").append(getUpdateBy()).append("\n");
		columnsBuffer.append("updateTime=").append(getUpdateTime()).append("\n");
		columnsBuffer.append("status=").append(getStatus()).append("\n");
		return columnsBuffer.toString();
	}
}
