/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import sqltoy.showcase.system.vo.base.AbstractAreaCodeVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * 地区代码表  		
 * AreaCodeVO generated by sys_area_code
 */
@SqlToyEntity
public class AreaCodeVO extends AbstractAreaCodeVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 2729820544404624270L;
	
	/** default constructor */
	public AreaCodeVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public AreaCodeVO(String areaCode)
	{
		this.areaCode=areaCode;
	}

	/** minimal constructor */
	public AreaCodeVO(String areaCode,String areaName,Integer showIndex,String status)
	{
		this.areaCode=areaCode;
		this.areaName=areaName;
		this.showIndex=showIndex;
		this.status=status;
	}

	/** full constructor */
	public AreaCodeVO(String areaCode,String areaName,String cityCode,String cityName,String provinceCode,String provinceName,Integer showIndex,String status)
	{
		this.areaCode=areaCode;
		this.areaName=areaName;
		this.cityCode=cityCode;
		this.cityName=cityName;
		this.provinceCode=provinceCode;
		this.provinceName=provinceName;
		this.showIndex=showIndex;
		this.status=status;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public AreaCodeVO clone() {
		try {
			// TODO Auto-generated method stub
			return (AreaCodeVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
