/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import sqltoy.showcase.system.vo.base.AbstractBigLobVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * 大数据类型存储  		
 * BigLobVO generated by sys_big_lob
 */
@SqlToyEntity
public class BigLobVO extends AbstractBigLobVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 4705607194903685476L;
	
	/** default constructor */
	public BigLobVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public BigLobVO(Integer id)
	{
		this.id=id;
	}

	/** minimal constructor */
	public BigLobVO(Integer id,Date createDate)
	{
		this.id=id;
		this.createDate=createDate;
	}

	/** full constructor */
	public BigLobVO(Integer id,String staffName,Date createDate,String comments,byte[] staffPhoto)
	{
		this.id=id;
		this.staffName=staffName;
		this.createDate=createDate;
		this.comments=comments;
		this.staffPhoto=staffPhoto;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public BigLobVO clone() {
		try {
			// TODO Auto-generated method stub
			return (BigLobVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
