/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import sqltoy.showcase.system.vo.base.AbstractMultpkItemVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * 复合主键关联子表  		
 * MultpkItemVO generated by sys_multpk_item
 */
@SqlToyEntity
public class MultpkItemVO extends AbstractMultpkItemVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7900653522368832821L;
	
	/** default constructor */
	public MultpkItemVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public MultpkItemVO(String goodsNo)
	{
		this.goodsNo=goodsNo;
	}

	/** minimal constructor */
	public MultpkItemVO(String goodsNo,Integer quantity,Double price)
	{
		this.goodsNo=goodsNo;
		this.quantity=quantity;
		this.price=price;
	}

	/** full constructor */
	public MultpkItemVO(String goodsNo,String bizType,String batchNo,Integer quantity,Double price)
	{
		this.goodsNo=goodsNo;
		this.bizType=bizType;
		this.batchNo=batchNo;
		this.quantity=quantity;
		this.price=price;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public MultpkItemVO clone() {
		try {
			// TODO Auto-generated method stub
			return (MultpkItemVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
