/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import java.io.Serializable;
import java.util.Date;
import sqltoy.showcase.system.vo.base.AbstractOrganInfoVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * 机构信息表  		
 * OrganInfoVO generated by sys_organ_info
 */
@SqlToyEntity
public class OrganInfoVO extends AbstractOrganInfoVO implements Serializable {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3200066048506181846L;
	
	/** default constructor */
	public OrganInfoVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public OrganInfoVO(String organId)
	{
		this.organId=organId;
	}

	/** minimal constructor */
	public OrganInfoVO(String organId,String organName,String operator,Date operateDate,String status)
	{
		this.organId=organId;
		this.organName=organName;
		this.operator=operator;
		this.operateDate=operateDate;
		this.status=status;
	}

	/** full constructor */
	public OrganInfoVO(String organId,String organName,String aliasName,String organCode,String organPid,String nodeRoute,Integer nodeLevel,Integer isLeaf,String operator,Date operateDate,String status)
	{
		this.organId=organId;
		this.organName=organName;
		this.aliasName=aliasName;
		this.organCode=organCode;
		this.organPid=organPid;
		this.nodeRoute=nodeRoute;
		this.nodeLevel=nodeLevel;
		this.isLeaf=isLeaf;
		this.operator=operator;
		this.operateDate=operateDate;
		this.status=status;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	private int count;
	
	/**
	 * 
	 */
	private String keywords;
	
	/**
	 * @return the count
	 */
	public int getCount() {
		return count;
	}

	/**
	 * @param count the count to set
	 */
	public void setCount(int count) {
		this.count = count;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public OrganInfoVO clone() {
		try {
			// TODO Auto-generated method stub
			return (OrganInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}

	/**
	 * @return the keywords
	 */
	public String getKeywords() {
		return keywords;
	}

	/**
	 * @param keywords the keywords to set
	 */
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}
	
}
