/**
 *@Generated by sagacity-quickvo 3.2
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import sqltoy.showcase.system.vo.base.AbstractStaffInfo1VO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sys_staff_info_1,Remark:员工信息表 	
 */
@SqlToyEntity
public class StaffInfo1VO extends AbstractStaffInfo1VO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 102620379630672613L;
	
	/** default constructor */
	public StaffInfo1VO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public StaffInfo1VO(String staffId)
	{
		this.staffId=staffId;
	}

	/** minimal constructor */
	public StaffInfo1VO(String staffId,String staffCode,String organId,String staffName,String operator,Date operateDate,String status)
	{
		this.staffId=staffId;
		this.staffCode=staffCode;
		this.organId=organId;
		this.staffName=staffName;
		this.operator=operator;
		this.operateDate=operateDate;
		this.status=status;
	}

	/** full constructor */
	public StaffInfo1VO(String staffId,String staffCode,String organId,String staffName,String sexType,String mobileTel,Date birthday,Date dutyDate,Date outDutyDate,String post,String nativePlace,String email,String operator,Date operateDate,String status)
	{
		this.staffId=staffId;
		this.staffCode=staffCode;
		this.organId=organId;
		this.staffName=staffName;
		this.sexType=sexType;
		this.mobileTel=mobileTel;
		this.birthday=birthday;
		this.dutyDate=dutyDate;
		this.outDutyDate=outDutyDate;
		this.post=post;
		this.nativePlace=nativePlace;
		this.email=email;
		this.operator=operator;
		this.operateDate=operateDate;
		this.status=status;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public StaffInfo1VO clone() {
		try {
			// TODO Auto-generated method stub
			return (StaffInfo1VO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
