/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import sqltoy.showcase.system.vo.base.AbstractSummaryCaseVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sys_summary_case,Remark:汇总计算演示表 	
 */
@SqlToyEntity
public class SummaryCaseVO extends AbstractSummaryCaseVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7274500950305491282L;
	
	/** default constructor */
	public SummaryCaseVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public SummaryCaseVO(String transId)
	{
		this.transId=transId;
	}

	/** minimal constructor */
	public SummaryCaseVO(String transId,Date transDate,String transChannel,Double transAmt)
	{
		this.transId=transId;
		this.transDate=transDate;
		this.transChannel=transChannel;
		this.transAmt=transAmt;
	}

	/** full constructor */
	public SummaryCaseVO(String transId,Date transDate,String transChannel,String transCode,Double transAmt)
	{
		this.transId=transId;
		this.transDate=transDate;
		this.transChannel=transChannel;
		this.transCode=transCode;
		this.transAmt=transAmt;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public SummaryCaseVO clone() {
		try {
			// TODO Auto-generated method stub
			return (SummaryCaseVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
