/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import sqltoy.showcase.system.vo.base.AbstractTerminalInfoVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sys_terminal_info 	
 */
@SqlToyEntity
public class TerminalInfoVO extends AbstractTerminalInfoVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8752026062446536348L;
	
	/** default constructor */
	public TerminalInfoVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public TerminalInfoVO(String terminalCode)
	{
		this.terminalCode=terminalCode;
	}


	/** full constructor */
	public TerminalInfoVO(String terminalCode,String terminalId,String deviceSn,Integer deviceType,String deviceTypeName,String posType,Integer deviceOwner,String activedDeviceType,String saleChannel,Integer deviceDrawMethod,String deviceCategory,Date openTime,Date closeTime,Date updateTime,String shopId,String merchantId,String merchantCode,String termClass,String isActive,Date activeTime,String isTouch,String signOrg,String branchOrganId,String maintainName,String maintainCode,String maintainOrg,String serviceOrg,Integer developPart,String developId,String status,String productClass,String mccCode,String mccType)
	{
		this.terminalCode=terminalCode;
		this.terminalId=terminalId;
		this.deviceSn=deviceSn;
		this.deviceType=deviceType;
		this.deviceTypeName=deviceTypeName;
		this.posType=posType;
		this.deviceOwner=deviceOwner;
		this.activedDeviceType=activedDeviceType;
		this.saleChannel=saleChannel;
		this.deviceDrawMethod=deviceDrawMethod;
		this.deviceCategory=deviceCategory;
		this.openTime=openTime;
		this.closeTime=closeTime;
		this.updateTime=updateTime;
		this.shopId=shopId;
		this.merchantId=merchantId;
		this.merchantCode=merchantCode;
		this.termClass=termClass;
		this.isActive=isActive;
		this.activeTime=activeTime;
		this.isTouch=isTouch;
		this.signOrg=signOrg;
		this.branchOrganId=branchOrganId;
		this.maintainName=maintainName;
		this.maintainCode=maintainCode;
		this.maintainOrg=maintainOrg;
		this.serviceOrg=serviceOrg;
		this.developPart=developPart;
		this.developId=developId;
		this.status=status;
		this.productClass=productClass;
		this.mccCode=mccCode;
		this.mccType=mccType;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public TerminalInfoVO clone() {
		try {
			// TODO Auto-generated method stub
			return (TerminalInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
