/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.system.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import sqltoy.showcase.system.vo.base.AbstractUnpivotDataVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0 行转列测试 UnpivotDataVO generated by sys_unpivot_data
 */
@SqlToyEntity
public class UnpivotDataVO extends AbstractUnpivotDataVO {
	/**
	 * 金额分类
	 */
	private String amountType;

	/**
	 * 交易金额
	 */
	private Double transAmount;
	/**
	 * 
	 */
	private static final long serialVersionUID = 7599915083136816655L;

	/** default constructor */
	public UnpivotDataVO() {
		super();
	}

	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public UnpivotDataVO(Date transDate) {
		this.transDate = transDate;
	}

	/** full constructor */
	public UnpivotDataVO(Date transDate, Double totalAmount, Double personAmount, Double companyAmount) {
		this.transDate = transDate;
		this.totalAmount = totalAmount;
		this.personAmount = personAmount;
		this.companyAmount = companyAmount;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	/**
	 * @todo vo columns to String
	 */
	public String toString() {
		return super.toString();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public UnpivotDataVO clone() {
		try {
			// TODO Auto-generated method stub
			return (UnpivotDataVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}

	/**
	 * @return the amountType
	 */
	public String getAmountType() {
		return amountType;
	}

	/**
	 * @param amountType the amountType to set
	 */
	public void setAmountType(String amountType) {
		this.amountType = amountType;
	}

	/**
	 * @return the transAmount
	 */
	public Double getTransAmount() {
		return transAmount;
	}

	/**
	 * @param transAmount the transAmount to set
	 */
	public void setTransAmount(Double transAmount) {
		this.transAmount = transAmount;
	}

}
