/**
 *@Generated by sagacity-quickvo 4.13
 */
package com.sagframe.sqltoy.showcase.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.math.BigInteger;
import com.sagframe.sqltoy.showcase.vo.base.AbstractBigintTableVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_bigint_table 	
 */
@SqlToyEntity
public class BigintTableVO extends AbstractBigintTableVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 9198414726863447076L;
	
	/** default constructor */
	public BigintTableVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public BigintTableVO(BigInteger id)
	{
		this.id=id;
	}


	/** full constructor */
	public BigintTableVO(BigInteger id,String name)
	{
		this.id=id;
		this.name=name;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public BigintTableVO clone() {
		try {
			return (BigintTableVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
