/**
 *@Generated by sagacity-quickvo 4.0
 */
package com.sagframe.sqltoy.showcase.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import com.sagframe.sqltoy.showcase.vo.base.AbstractStaffAuthOrgsVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_staff_auth_orgs,Remark:员工机构授权表 	
 */
@SqlToyEntity
public class StaffAuthOrgsVO extends AbstractStaffAuthOrgsVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1827043301247093219L;
	
	/**
	 * 请绝对不要在此类中重复定义Abstract类中的对应表字段的属性,易导致属性失去@Column关联表字段的注解特征,无法正确生成相应的sql
	 * 如覆盖定义了属性C,原本生成 insert into tableName (A,B,C) values(?,?,?) 变成了 insert into tableName (A,B) values(?,?)
	 */
	 
	/** default constructor */
	public StaffAuthOrgsVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public StaffAuthOrgsVO(String authId)
	{
		this.authId=authId;
	}


	/** full constructor */
	public StaffAuthOrgsVO(String authId,String staffId,String organId,Integer showIndex,String createBy,Date createTime,String updateBy,Date updateTime,Integer status)
	{
		this.authId=authId;
		this.staffId=staffId;
		this.organId=organId;
		this.showIndex=showIndex;
		this.createBy=createBy;
		this.createTime=createTime;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
		this.status=status;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	
	//请绝对不要在此类中重复定义Abstract类中的对应表字段的属性,易导致属性失去@Column关联表字段的注解特征,无法正确生成相应的sql
	//如覆盖定义了属性C,原本生成 insert into tableName (A,B,C) values(?,?,?) 变成了 insert into tableName (A,B) values(?,?)
	 
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public StaffAuthOrgsVO clone() {
		try {
			// TODO Auto-generated method stub
			return (StaffAuthOrgsVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
