/**
 *@Generated by sagacity-quickvo 4.13
 */
package com.sagframe.sqltoy.showcase.vo;

import java.math.BigInteger;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sagframe.sqltoy.showcase.vo.base.AbstractTestVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_test 	
 */
@SqlToyEntity
public class TestVO extends AbstractTestVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 729857432058337641L;
	
	/** default constructor */
	public TestVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/


	/** full constructor */
	public TestVO(Boolean id,String name,BigInteger sallary)
	{
		this.id=id;
		this.name=name;
		this.sallary=sallary;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public TestVO clone() {
		try {
			return (TestVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
