/**
 *@Generated by sagacity-quickvo 4.0
 */
package com.sagframe.sqltoy.showcase.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.util.Date;
import com.sagframe.sqltoy.showcase.vo.base.AbstractUserLogVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_user_log,Remark:用户日志表 	
 */
@SqlToyEntity
public class UserLogVO extends AbstractUserLogVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1296922598783858512L;
	
	/**
	 * 请绝对不要在此类中重复定义Abstract类中的对应表字段的属性,易导致属性失去@Column关联表字段的注解特征,无法正确生成相应的sql
	 * 如覆盖定义了属性C,原本生成 insert into tableName (A,B,C) values(?,?,?) 变成了 insert into tableName (A,B) values(?,?)
	 */
	 
	/** default constructor */
	public UserLogVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public UserLogVO(String logId)
	{
		this.logId=logId;
	}

	/** minimal constructor */
	public UserLogVO(String logId,String userId,Date logTime,Date logDate,String logType,String channel,String contents)
	{
		this.logId=logId;
		this.userId=userId;
		this.logTime=logTime;
		this.logDate=logDate;
		this.logType=logType;
		this.channel=channel;
		this.contents=contents;
	}

	/** full constructor */
	public UserLogVO(String logId,String userId,String terminalIp,String deviceCode,Date logTime,Date logDate,String logType,String channel,String contents)
	{
		this.logId=logId;
		this.userId=userId;
		this.terminalIp=terminalIp;
		this.deviceCode=deviceCode;
		this.logTime=logTime;
		this.logDate=logDate;
		this.logType=logType;
		this.channel=channel;
		this.contents=contents;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	
	//请绝对不要在此类中重复定义Abstract类中的对应表字段的属性,易导致属性失去@Column关联表字段的注解特征,无法正确生成相应的sql
	//如覆盖定义了属性C,原本生成 insert into tableName (A,B,C) values(?,?,?) 变成了 insert into tableName (A,B) values(?,?)
	 
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public UserLogVO clone() {
		try {
			// TODO Auto-generated method stub
			return (UserLogVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
