/**
 *@Generated by sagacity-quickvo 4.0
 */
package com.sagframe.sqltoy.showcase.vo;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.sagacity.sqltoy.config.annotation.Sharding;
import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import org.sagacity.sqltoy.config.annotation.Strategy;

import com.sagframe.sqltoy.showcase.vo.base.AbstractUserLogVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0 Table: sqltoy_user_log,Remark:用户日志表
 */
/*
 * db则是分库策略配置,table 则是分表策略配置，可以同时配置也可以独立配置
 * 策略name要跟spring中的bean定义name一致,fields表示要以对象的哪几个字段值作为判断依据,可以一个或多个字段
 * maxConcurrents:可选配置，表示最大并行数 maxWaitSeconds:可选配置，表示最大等待秒数
 */
@Sharding(db = @Strategy(name = "hashBalanceDBSharding", fields = { "userId" }),
		// table = @Strategy(name = "hashBalanceSharding", fields = {"userId" }),
		maxConcurrents = 10, maxWaitSeconds = 1800)
@SqlToyEntity
public class UserLogVO extends AbstractUserLogVO {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1296922598783858512L;

	/** default constructor */
	public UserLogVO() {
		super();
	}

	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public UserLogVO(String logId) {
		this.logId = logId;
	}

	/** minimal constructor */
	public UserLogVO(String logId, String userId, LocalDateTime logTime, LocalDate logDate, String logType,
			String channel, String contents) {
		this.logId = logId;
		this.userId = userId;
		this.logTime = logTime;
		this.logDate = logDate;
		this.logType = logType;
		this.channel = channel;
		this.contents = contents;
	}

	/** full constructor */
	public UserLogVO(String logId, String userId, String terminalIp, String deviceCode, LocalDateTime logTime,
			LocalDate logDate, String logType, String channel, String contents) {
		this.logId = logId;
		this.userId = userId;
		this.terminalIp = terminalIp;
		this.deviceCode = deviceCode;
		this.logTime = logTime;
		this.logDate = logDate;
		this.logType = logType;
		this.channel = channel;
		this.contents = contents;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	/**
	 * @todo vo columns to String
	 */
	public String toString() {
		return super.toString();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public UserLogVO clone() {
		try {
			// TODO Auto-generated method stub
			return (UserLogVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}

}
