/**
 *@Generated by sagacity-quickvo 4.13
 */
package com.sqltoy.quickstart.vo;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sqltoy.quickstart.vo.base.AbstractComplexpkHeadVO;

/**
 * @project sqltoy-quickstart
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_complexpk_head,Remark:复合主键级联操作主表 	
 */
@SqlToyEntity
public class ComplexpkHeadVO extends AbstractComplexpkHeadVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 8333098323861603937L;
	
	/** default constructor */
	public ComplexpkHeadVO() {
		super();
	}
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public ComplexpkHeadVO(LocalDate transDate,String transCode)
	{
		this.transDate=transDate;
		this.transCode=transCode;
	}


	/** full constructor */
	public ComplexpkHeadVO(LocalDate transDate,String transCode,BigDecimal totalCnt,BigDecimal totalAmt,String createBy,LocalDateTime createTime,String updateBy,LocalDateTime updateTime)
	{
		this.transDate=transDate;
		this.transCode=transCode;
		this.totalCnt=totalCnt;
		this.totalAmt=totalAmt;
		this.createBy=createBy;
		this.createTime=createTime;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
	}

	/**
	 * mapping sqltoy_complexpk_item data to sqltoy_complexpk_head oneToMany List
	 */
	public void mappingComplexpkItemVOs(List<ComplexpkHeadVO> mainSet,List<ComplexpkItemVO> itemSet)
    {
    	if(mainSet==null || mainSet.isEmpty() || itemSet==null||itemSet.isEmpty())
    		return;
    	ComplexpkHeadVO main;
    	ComplexpkItemVO item;
    	for(int i=0;i<mainSet.size();i++){
    		main=mainSet.get(i);
    		if(itemSet.size()==0)
    			break;
    		for(int j=0;j<itemSet.size();j++){
    			item=itemSet.get(j);
    			if(main.getTransDate().equals(item.getTransDate())&& main.getTransCode().equals(item.getTransId())){
    			  main.complexpkItemVOs.add(item);
    			  itemSet.remove(j);
    			  j--;
    			}
    		}
    	}
    }
	/*---end-constructor-area---don't-update-this-area--*/
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public ComplexpkHeadVO clone() {
		try {
			return (ComplexpkHeadVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
