/**
 *@Generated by sagacity-quickvo 4.13
 */
package com.sqltoy.quickstart.vo;

import java.math.BigDecimal;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;

import com.sqltoy.quickstart.vo.base.AbstractFruitOrderVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * Table: sqltoy_fruit_order,Remark:查询汇总演示-水果订单表 	
 */
@SqlToyEntity
public class FruitOrderVO extends AbstractFruitOrderVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 6351778226462253330L;
	
	/** default constructor */
	public FruitOrderVO() {
		super();
	}
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public FruitOrderVO(String fruitName,Integer orderMonth)
	{
		this.fruitName=fruitName;
		this.orderMonth=orderMonth;
	}


	/** full constructor */
	public FruitOrderVO(String fruitName,Integer orderMonth,BigDecimal saleCount,BigDecimal salePrice,BigDecimal totalAmt)
	{
		this.fruitName=fruitName;
		this.orderMonth=orderMonth;
		this.saleCount=saleCount;
		this.salePrice=salePrice;
		this.totalAmt=totalAmt;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	/**
     *@todo vo columns to String
     */
    @Override
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	@Override
	public FruitOrderVO clone() {
		try {
			return (FruitOrderVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
