package org.sagacity.sqltoy.dialect.utils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import org.sagacity.sqltoy.SqlToyConstants;
import org.sagacity.sqltoy.callback.PreparedStatementResultHandler;
import org.sagacity.sqltoy.config.model.PKStrategy;
import org.sagacity.sqltoy.model.ColumnMeta;
import org.sagacity.sqltoy.model.DBProfile;
import org.sagacity.sqltoy.model.LockMode;
import org.sagacity.sqltoy.model.TableMeta;
import org.sagacity.sqltoy.utils.SqlUtil;
import org.sagacity.sqltoy.utils.StringUtil;

/**
 * @project sagacity-sqltoy
 * @description SAP HANA 2.0数据库方言工具类:锁语句、load/loadAll、表元数据(SYS字典视图)
 *              HANA语法近oracle(nvl/merge into/sequence.nextval/dummy虚表/大写标识符),
 *              分页为标准offset/fetch形态(复用OracleDialectUtils),随机数为rand()+limit
 *              (复用DefaultDialectUtils),本类仅承载HANA特有部分: 1、锁:skip locked对应HANA的FOR
 *              UPDATE IGNORE
 *              2、元数据:HANA无user_tab_comments/user_col_comments,备注取SYS.TABLES/
 *              SYS.VIEWS/SYS.TABLE_COLUMNS的COMMENTS列
 * @author zhongxuchen
 * @version v1.0,Date:2026-09-11
 */
public class HanaDialectUtils {

	/**
	 * 主键策略是identity或sequence时，主键值允许不由数据库内部自动产生，可人工赋值 (hana的identity为GENERATED BY
	 * DEFAULT AS IDENTITY,允许显式赋值但会与内部计数脱钩, 与dm同规:identity策略交由数据库产生)
	 * 
	 * @param pkStrategy
	 * @return
	 */
	public static boolean allowAssignPKValue(PKStrategy pkStrategy) {
		if (pkStrategy == null) {
			return true;
		}
		if (pkStrategy.equals(PKStrategy.SEQUENCE)) {
			return true;
		}
		// identity字段不由人工赋值,经getGeneratedKeys回填
		if (pkStrategy.equals(PKStrategy.IDENTITY)) {
			return false;
		}
		return true;
	}

	/**
	 * hana的锁语句:与oracle同族(for update wait n/nowait),但跳过已锁行hana为FOR UPDATE IGNORE
	 * (无skip locked语法)
	 * 
	 * @param sql
	 * @param profile
	 * @param lockMode
	 * @param lockWaitTimeout
	 * @return
	 */
	public static String getLockSql(String sql, DBProfile profile, LockMode lockMode, int lockWaitTimeout) {
		return DefaultDialectUtils.getLockSql(sql, profile.getDbType(), lockMode, lockWaitTimeout, true,
				" for update ignore ", true);
	}

	/**
	 * 获取表清单(含备注):hana无oracle的user_tab_comments字典,以SYS.TABLES/SYS.VIEWS的
	 * COMMENTS列组织(与OracleDialectUtils.getTables同构,保证TableApi.getTables备注语义);
	 * hana的表分区为物理分区(不产生分区子表清单项),无需pg系的主表过滤; 未加引号标识符hana统一大写存储,pattern按方言大小写策略转换
	 * 
	 * @param catalog
	 * @param schema
	 * @param tableName
	 * @param conn
	 * @param profile
	 * @param dialect
	 * @return
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	public static List<TableMeta> getTables(String catalog, String schema, String tableName, Connection conn,
			DBProfile profile) throws Exception {
		String dialect = profile.getDialect();
		final String realTableName = SqlToyConstants.getDialectLowcaseStrategyName(tableName, dialect);
		// schema未指定时取当前用户默认schema(hana的schema与用户同名)
		final boolean useCurrentSchema = StringUtil.isBlank(schema);
		final String realSchema = useCurrentSchema ? null : schema.toUpperCase(Locale.ROOT);
		String schemaCond = useCurrentSchema ? "SCHEMA_NAME=CURRENT_SCHEMA" : "SCHEMA_NAME=?";
		StringBuilder sql = new StringBuilder(
				"select TABLE_NAME,TABLE_TYPE,COMMENTS from (select TABLE_NAME,'TABLE' as TABLE_TYPE,COMMENTS from SYS.TABLES where "
						+ schemaCond
						+ " and IS_TEMPORARY='FALSE' union all select VIEW_NAME,'VIEW',COMMENTS from SYS.VIEWS where "
						+ schemaCond + ")");
		if (StringUtil.isNotBlank(realTableName)) {
			sql.append(" where TABLE_NAME like ?");
		}
		PreparedStatement pst = conn.prepareStatement(sql.toString());
		// 设置全局statementTimeout，默认为null
		if (SqlToyConstants.defaultStatementTimeout != null && SqlToyConstants.defaultStatementTimeout > 0) {
			pst.setQueryTimeout(SqlToyConstants.defaultStatementTimeout);
		}
		ResultSet rs = null;
		// 通过preparedStatementProcess反调，第二个参数是pst
		return (List<TableMeta>) SqlUtil.preparedStatementProcess(null, pst, rs, new PreparedStatementResultHandler() {
			@Override
			public void execute(Object rowData, PreparedStatement pst, ResultSet rs) throws Exception {
				try {
					int idx = 1;
					if (!useCurrentSchema) {
						pst.setString(idx++, realSchema);
						pst.setString(idx++, realSchema);
					}
					if (StringUtil.isNotBlank(realTableName)) {
						if (realTableName.contains("%")) {
							pst.setString(idx, realTableName);
						} else {
							pst.setString(idx, "%" + realTableName + "%");
						}
					}
					rs = pst.executeQuery();
					List<TableMeta> tables = new ArrayList<TableMeta>();
					while (rs.next()) {
						TableMeta tableMeta = new TableMeta();
						tableMeta.setTableName(rs.getString("TABLE_NAME"));
						tableMeta.setType(rs.getString("TABLE_TYPE"));
						tableMeta.setRemarks(StringUtil.escapeComment(rs.getString("COMMENTS")));
						tables.add(tableMeta);
					}
					this.setResult(tables);
				} catch (Exception e) {
					throw e;
				} finally {
					if (rs != null) {
						rs.close();
						rs = null;
					}
				}
			}
		});
	}

	/**
	 * 获取表字段元数据:通用JDBC元数据(类型/精度/可空/默认值/IS_GENERATEDCOLUMN计算列识别) +
	 * SYS.TABLE_COLUMNS.COMMENTS备注补全(与OracleDialectUtils.getTableColumns同构)
	 * 
	 * @param catalog
	 * @param schema
	 * @param tableName
	 * @param conn
	 * @param profile
	 * @param dialect
	 * @return
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	public static List<ColumnMeta> getTableColumns(String catalog, String schema, String tableName, Connection conn,
			DBProfile profile) throws Exception {
		String dialect = profile.getDialect();
		List<ColumnMeta> tableColumns = DefaultDialectUtils.getTableColumns(catalog, schema, tableName, conn, profile);
		// 表名按方言大小写策略转换(hana大写存储,小写原样绑定查不到列备注)
		final String realTableName = SqlToyConstants.getDialectLowcaseStrategyName(tableName, dialect);
		final boolean useCurrentSchema = StringUtil.isBlank(schema);
		final String realSchema = useCurrentSchema ? null : schema.toUpperCase(Locale.ROOT);
		String sql = "select COLUMN_NAME,COMMENTS from SYS.TABLE_COLUMNS where "
				+ (useCurrentSchema ? "SCHEMA_NAME=CURRENT_SCHEMA" : "SCHEMA_NAME=?") + " and TABLE_NAME=?";
		PreparedStatement pst = conn.prepareStatement(sql);
		// 设置全局statementTimeout，默认为null
		if (SqlToyConstants.defaultStatementTimeout != null && SqlToyConstants.defaultStatementTimeout > 0) {
			pst.setQueryTimeout(SqlToyConstants.defaultStatementTimeout);
		}
		ResultSet rs = null;
		// 通过preparedStatementProcess反调，第二个参数是pst
		Map<String, String> colMap = (Map<String, String>) SqlUtil.preparedStatementProcess(null, pst, rs,
				new PreparedStatementResultHandler() {
					@Override
					public void execute(Object rowData, PreparedStatement pst, ResultSet rs) throws Exception {
						try {
							int idx = 1;
							if (!useCurrentSchema) {
								pst.setString(idx++, realSchema);
							}
							pst.setString(idx, realTableName);
							rs = pst.executeQuery();
							Map<String, String> colComments = new HashMap<String, String>();
							String comment;
							String colName;
							while (rs.next()) {
								comment = rs.getString("COMMENTS");
								colName = rs.getString("COLUMN_NAME");
								if (colName != null && comment != null) {
									colComments.put(colName.toUpperCase(Locale.ROOT), comment);
								}
							}
							this.setResult(colComments);
						} catch (Exception e) {
							throw e;
						} finally {
							if (rs != null) {
								rs.close();
								rs = null;
							}
						}
					}
				});
		if (colMap != null && !colMap.isEmpty()) {
			for (ColumnMeta col : tableColumns) {
				col.setComments(colMap.get(col.getColName().toUpperCase(Locale.ROOT)));
			}
		}
		return tableColumns;
	}
}
