/**
 *@Generated by QuickVO Tools 2.0
 */
package sqltoy.showcase.sagacity.vo;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import java.sql.Timestamp;
import sqltoy.showcase.sagacity.vo.base.AbstractDictDetailVO;

/**
 * @project sqltoy-showcase
 * @author zhongxuchen
 * @version 1.0.0
 * 数据字典明细表  		
 * DictDetailVO generated by sag_dict_detail
 */
@SqlToyEntity
public class DictDetailVO extends AbstractDictDetailVO {	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7387364490848361587L;
	
	/** default constructor */
	public DictDetailVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public DictDetailVO(String dictTypeCode,String dictKey)
	{
		this.dictTypeCode=dictTypeCode;
		this.dictKey=dictKey;
	}

	/** minimal constructor */
	public DictDetailVO(String dictTypeCode,String dictKey,String dictName,Integer showIndex,String updateBy,Timestamp updateTime,String status)
	{
		this.dictTypeCode=dictTypeCode;
		this.dictKey=dictKey;
		this.dictName=dictName;
		this.showIndex=showIndex;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
		this.status=status;
	}

	/** full constructor */
	public DictDetailVO(String dictTypeCode,String dictKey,String dictName,Integer showIndex,String comments,String segment,String updateBy,Timestamp updateTime,String status)
	{
		this.dictTypeCode=dictTypeCode;
		this.dictKey=dictKey;
		this.dictName=dictName;
		this.showIndex=showIndex;
		this.comments=comments;
		this.segment=segment;
		this.updateBy=updateBy;
		this.updateTime=updateTime;
		this.status=status;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public DictDetailVO clone() {
		try {
			// TODO Auto-generated method stub
			return (DictDetailVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
