/**
 *@Generated by sagacity-quickvo 4.13
 */
package com.sagframe.sqltoy.showcase.vo.base;

import java.io.Serializable;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;
import org.sagacity.sqltoy.config.annotation.Column;


/**
 * @project sqltoy-showcase
 * @version 1.0.0
 * Table: sqltoy_fruit_order  
 */
@Entity(tableName="sqltoy_fruit_order")
public abstract class AbstractFruitOrderVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //fruitName,orderMonth,saleCount,saleAmt,totalAmt
	 
	 //not null properties
	 //fruitName,orderMonth,saleCount,saleAmt,totalAmt

	/**
	 * 
	 */
	private static final long serialVersionUID = 3651282017388714610L;
	
	@Column(name="fruit_name",length=100L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String fruitName;
	
	@Column(name="order_month",length=10L,type=java.sql.Types.INTEGER,nullable=false)
	protected Integer orderMonth;
	
	@Column(name="sale_count",length=10L,type=java.sql.Types.INTEGER,nullable=false)
	protected Long saleCount;
	
	@Column(name="sale_amt",length=10L,type=java.sql.Types.INTEGER,nullable=false)
	protected Long saleAmt;
	
	@Column(name="total_amt",length=10L,type=java.sql.Types.INTEGER,nullable=false)
	protected Long totalAmt;
	

	/** default constructor */
	public AbstractFruitOrderVO() {
	}
	


	/** full constructor */
	public AbstractFruitOrderVO(String fruitName,Integer orderMonth,Long saleCount,Long saleAmt,Long totalAmt)
	{
		this.fruitName=fruitName;
		this.orderMonth=orderMonth;
		this.saleCount=saleCount;
		this.saleAmt=saleAmt;
		this.totalAmt=totalAmt;
	}
	
	/**
	 *@param fruitName the fruitName to set
	 */
	public AbstractFruitOrderVO setFruitName(String fruitName) {
		this.fruitName=fruitName;
		return this;
	}
		
	/**
	 *@return the FruitName
	 */
	public String getFruitName() {
	    return this.fruitName;
	}
	
	/**
	 *@param orderMonth the orderMonth to set
	 */
	public AbstractFruitOrderVO setOrderMonth(Integer orderMonth) {
		this.orderMonth=orderMonth;
		return this;
	}
		
	/**
	 *@return the OrderMonth
	 */
	public Integer getOrderMonth() {
	    return this.orderMonth;
	}
	
	/**
	 *@param saleCount the saleCount to set
	 */
	public AbstractFruitOrderVO setSaleCount(Long saleCount) {
		this.saleCount=saleCount;
		return this;
	}
		
	/**
	 *@return the SaleCount
	 */
	public Long getSaleCount() {
	    return this.saleCount;
	}
	
	/**
	 *@param saleAmt the saleAmt to set
	 */
	public AbstractFruitOrderVO setSaleAmt(Long saleAmt) {
		this.saleAmt=saleAmt;
		return this;
	}
		
	/**
	 *@return the SaleAmt
	 */
	public Long getSaleAmt() {
	    return this.saleAmt;
	}
	
	/**
	 *@param totalAmt the totalAmt to set
	 */
	public AbstractFruitOrderVO setTotalAmt(Long totalAmt) {
		this.totalAmt=totalAmt;
		return this;
	}
		
	/**
	 *@return the TotalAmt
	 */
	public Long getTotalAmt() {
	    return this.totalAmt;
	}



	/**
     * @todo vo columns to String
     */
    @Override
	public String toString() {
		StringBuilder columnsBuffer=new StringBuilder();
		columnsBuffer.append("fruitName=").append(getFruitName()).append("\n");
		columnsBuffer.append("orderMonth=").append(getOrderMonth()).append("\n");
		columnsBuffer.append("saleCount=").append(getSaleCount()).append("\n");
		columnsBuffer.append("saleAmt=").append(getSaleAmt()).append("\n");
		columnsBuffer.append("totalAmt=").append(getTotalAmt()).append("\n");
		return columnsBuffer.toString();
	}
}
