/**
 *@Generated by QuickVO Tools 1.5 
 */
package org.sagacity.sqltoy.demo.vo;

import java.util.Date;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import org.sagacity.sqltoy.demo.vo.base.AbstractOrganInfoVO;

/**
 * @project sqltoy-orm
 * @author chenrenfei@lakala.com
 * @version 1.0.0
 * 机构信息表  		
 * OrganInfoVO generated by TEST_ORGAN_INFO
 */
@SqlToyEntity
public class OrganInfoVO extends AbstractOrganInfoVO {	
	/** default constructor */
	public OrganInfoVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public OrganInfoVO(String organId)
	{
		this.organId=organId;
	}

	/** minimal constructor */
	public OrganInfoVO(String organId,String organName,String operator,Date operateDate,Integer enabled)
	{
		this.organId=organId;
		this.organName=organName;
		this.operator=operator;
		this.operateDate=operateDate;
		this.enabled=enabled;
	}

	/** full constructor */
	public OrganInfoVO(String organId,String organName,String aliasName,String organCode,String manager,String organPid,String nodeRoute,Integer nodeLevel,Integer isLeaf,String operator,Date operateDate,Integer enabled)
	{
		this.organId=organId;
		this.organName=organName;
		this.aliasName=aliasName;
		this.organCode=organCode;
		this.manager=manager;
		this.organPid=organPid;
		this.nodeRoute=nodeRoute;
		this.nodeLevel=nodeLevel;
		this.isLeaf=isLeaf;
		this.operator=operator;
		this.operateDate=operateDate;
		this.enabled=enabled;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public OrganInfoVO clone() {
		try {
			// TODO Auto-generated method stub
			return (OrganInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
