/**
 *@Generated by QuickVO Tools 1.5 
 */
package org.sagacity.sqltoy.demo.vo;

import java.util.Date;

import org.sagacity.sqltoy.config.annotation.Sharding;
import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import org.sagacity.sqltoy.config.annotation.Strategy;
import org.sagacity.sqltoy.demo.vo.base.AbstractStaffInfoVO;

/**
 * @project sqltoy-orm
 * @author chenrenfei@lakala.com
 * @version 1.0.0 员工信息表 StaffInfoVO generated by SYS_STAFF_INFO
 */
@SqlToyEntity
@Sharding(db = @Strategy(name = "hashModeStrategy", fields = {
		"id" }), table = @Strategy(name = "hashModeStrategy", fields = {
				"idCard" }), maxConcurrents = 10, maxWaitSeconds = 3600)
public class StaffInfoVO extends AbstractStaffInfoVO {
	/** default constructor */
	public StaffInfoVO() {
		super();
	}

	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public StaffInfoVO(String staffId) {
		this.staffId = staffId;
	}

	/** minimal constructor */
	public StaffInfoVO(String staffId, String staffCode, String organId, String staffName, String operator,
			Date operateDate, Integer enabled) {
		this.staffId = staffId;
		this.staffCode = staffCode;
		this.organId = organId;
		this.staffName = staffName;
		this.operator = operator;
		this.operateDate = operateDate;
		this.enabled = enabled;
	}

	/** full constructor */
	public StaffInfoVO(String staffId, String staffCode, String organId, String staffName, String englishName,
			String sexType, String linkPhone, Date birthday, Date dutyDate, Date outDutyDate, String post, byte[] photo,
			String email, Integer isVirtual, String operator, Date operateDate, Integer enabled) {
		this.staffId = staffId;
		this.staffCode = staffCode;
		this.organId = organId;
		this.staffName = staffName;
		this.englishName = englishName;
		this.sexType = sexType;
		this.linkPhone = linkPhone;
		this.birthday = birthday;
		this.dutyDate = dutyDate;
		this.outDutyDate = outDutyDate;
		this.post = post;
		this.photo = photo;
		this.email = email;
		this.isVirtual = isVirtual;
		this.operator = operator;
		this.operateDate = operateDate;
		this.enabled = enabled;
	}

	/*---end-constructor-area---don't-update-this-area--*/

	/**
	 * @todo vo columns to String
	 */
	public String toString() {
		return super.toString();
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public StaffInfoVO clone() {
		try {
			// TODO Auto-generated method stub
			return (StaffInfoVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}

}
