/**
 *@Generated by QuickVO Tools 1.6
 */
package org.sagacity.sqltoy.demo.vo;

import java.util.Date;

import org.sagacity.sqltoy.config.annotation.SqlToyEntity;
import org.sagacity.sqltoy.demo.vo.base.AbstractTestVO;

/**
 * @project sqltoy-orm
 * @author chenrenfei@lakala.com
 * @version 1.0.0
 * 验证表  		
 * TestVO generated by SAG_TEST
 */
@SqlToyEntity
public class TestVO extends AbstractTestVO {	
	/** default constructor */
	public TestVO() {
		super();
	}
	
	/*---begin-constructor-area---don't-update-this-area--*/
	/** pk constructor */
	public TestVO(Integer staffId)
	{
		this.staffId=staffId;
	}


	/** full constructor */
	public TestVO(Integer staffId,String name,Date createTime)
	{
		this.staffId=staffId;
		this.name=name;
		this.createTime=createTime;
	}

	/*---end-constructor-area---don't-update-this-area--*/
	
	/**
     *@todo vo columns to String
     */
	public String toString() {
		return super.toString();
	}
	
	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#clone()
	 */
	public TestVO clone() {
		try {
			// TODO Auto-generated method stub
			return (TestVO) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
