/**
 *@Generated by QuickVO Tools 1.6
 */
package org.sagacity.sqltoy.demo.vo.base;

import java.io.Serializable;
import java.util.Date;

import org.sagacity.sqltoy.config.annotation.Column;
import org.sagacity.sqltoy.config.annotation.Entity;
import org.sagacity.sqltoy.config.annotation.Id;


/**
 * @project sqltoy-orm
 * @version 1.0.0
 * SEQ主键测试表    			
 * PkSequenceVO generated by TEST_PK_SEQUENCE
 */
@Entity(tableName="TEST_PK_SEQUENCE")
public abstract class AbstractPkSequenceVO implements Serializable,
	java.lang.Cloneable {
	 /*--------------- properties string,handier to copy ---------------------*/
	 //full properties 
	 //id,name,createTime,sallary
	 
	 //not null properties
	 //id,name

	/**
	 * 主键值
	 */
	@Id(strategy="sequence",sequence="SEQ_TEST_PK_ID")
	@Column(name="ID",length=8L,type=java.sql.Types.INTEGER,nullable=false)
	protected Integer id;
	
	/**
	 * 姓名
	 */
	@Column(name="NAME",length=30L,type=java.sql.Types.VARCHAR,nullable=false)
	protected String name;
	
	/**
	 * 创建日期
	 */
	@Column(name="CREATE_TIME",length=7L,defaultValue="SYSDATE",type=java.sql.Types.DATE,nullable=true)
	protected Date createTime;
	
	/**
	 * 基本工资
	 */
	@Column(name="SALLARY",length=8L,type=java.sql.Types.DOUBLE,nullable=true)
	protected Double sallary;
	


	/** default constructor */
	public AbstractPkSequenceVO() {
	}
	
	/** pk constructor */
	public AbstractPkSequenceVO(Integer id)
	{
		this.id=id;
	}

	/** minimal constructor */
	public AbstractPkSequenceVO(Integer id,String name)
	{
		this.id=id;
		this.name=name;
	}

	/** full constructor */
	public AbstractPkSequenceVO(Integer id,String name,Date createTime,Double sallary)
	{
		this.id=id;
		this.name=name;
		this.createTime=createTime;
		this.sallary=sallary;
	}
	
	/**
	 *@param id the id to set
	 */
	public void setId(Integer id) {
		this.id=id;
	}
		
	/**
	 *@return the Id
	 */
	public Integer getId() {
	    return this.id;
	}
	
	/**
	 *@param name the name to set
	 */
	public void setName(String name) {
		this.name=name;
	}
		
	/**
	 *@return the Name
	 */
	public String getName() {
	    return this.name;
	}
	
	/**
	 *@param createTime the createTime to set
	 */
	public void setCreateTime(Date createTime) {
		this.createTime=createTime;
	}
		
	/**
	 *@return the CreateTime
	 */
	public Date getCreateTime() {
	    return this.createTime;
	}
	
	/**
	 *@param sallary the sallary to set
	 */
	public void setSallary(Double sallary) {
		this.sallary=sallary;
	}
		
	/**
	 *@return the Sallary
	 */
	public Double getSallary() {
	    return this.sallary;
	}




	/**
     * @todo vo columns to String
     */
	public String toString() {
		StringBuffer columnsBuffer=new StringBuffer();
		columnsBuffer.append("id=").append(getId()).append("\n");
		columnsBuffer.append("name=").append(getName()).append("\n");
		columnsBuffer.append("createTime=").append(getCreateTime()).append("\n");
		columnsBuffer.append("sallary=").append(getSallary()).append("\n");
		return columnsBuffer.toString();
	}
}
